apiVersion: v2
name: llm-services
description: Authenticated Magda LLM facade
version: 7.0.0
kubeVersion: ">= 1.24.0-0"
annotations:
  magdaModuleType: core
dependencies:
  - name: litellm
    version: 7.0.0
    repository: file://../litellm
    condition: litellm.enabled
