apiVersion: v2
name: "magda-local-auth-test-deployment"
description: ""
version: "6.1.2-pr.3759.1"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: magda-core
    version: 6.1.2-pr.3759.1
    repository: "file://../magda-core"
