// @flow
export const actionTypes = {
    REQUEST_DATASET_FROM_CONNECTOR: "REQUEST_DATASET_FROM_CONNECTOR",
    RECEIVE_DATASET_FROM_CONNECTOR: "RECEIVE_DATASET_FROM_CONNECTOR",
    REQUEST_DATASET_FROM_CONNECTOR_ERROR:
        "REQUEST_DATASET_FROM_CONNECTOR_ERROR",

    REQUEST_WHO_AM_I: "REQUEST_WHO_AM_I",
    RECEIVE_WHO_AM_I_SIGNED_IN: "RECEIVE_WHO_AM_I_SIGNED_IN",
    RECEIVE_WHO_AM_I_SIGNED_OUT: "RECEIVE_WHO_AM_I_SIGNED_OUT",
    RECEIVE_WHO_AM_I_ERROR: "RECEIVE_WHO_AM_I_ERROR",

    // manage connectors
    REQUEST_CONNECTORS: "REQUEST_CONNECTORS",
    RECEIVE_CONNECTORS: "RECEIVE_CONNECTORS",
    REQUEST_CONNECTORS_ERROR: "REQUEST_CONNECTORS_ERROR",

    // manage connectors
    REQUEST_DATASET_SEARCH_RESULTS: "REQUEST_DATASET_SEARCH_RESULTS",
    RECEIVE_DATASET_SEARCH_RESULTS: "RECEIVE_DATASET_SEARCH_RESULTS",
    REQUEST_DATASET_SEARCH_RESULTS_ERROR:
        "REQUEST_DATASET_SEARCH_RESULTS_ERROR",

    // edit connecor config
    REQUEST_CONNECTOR_CONFIG: "REQUEST_CONNECTOR_CONFIG",
    RECEIVE_CONNECTOR_CONFIG: "RECEIVE_CONNECTOR_CONFIG",
    REQUEST_CONNECTOR_CONFIG_ERROR: "REQUEST_CONNECTOR_CONFIG_ERROR",

    // Update CONNECTOR
    UPDATE_CONNECTOR: "UPDATE_CONNECTOR",
    UPDATE_CONNECTOR_SUCCESS: "UPDATE_CONNECTOR_SUCCESS",
    UPDATE_CONNECTOR_FAILURE: "UPDATE_CONNECTOR_FAILURE",

    // Update CONNECTOR
    CREATE_CONNECTOR: "CREATE_CONNECTOR",
    CREATE_CONNECTOR_SUCCESS: "CREATE_CONNECTOR_SUCCESS",
    CREATE_CONNECTOR_ERROR: "CREATE_CONNECTOR_ERROR",
    RESET_CREATE_CONNECTOR: "RESET_CREATE_CONNECTOR",

    SIGN_UP: "SIGN_UP",
    SIGN_IN: "SIGN_IN",
    SIGNED_IN: "SIGNED_IN",
    SIGN_OUT: "SIGN_OUT",
    SIGNED_OUT: "SIGNED_OUT",

    REQUEST_SIGN_OUT: "REQUEST_SIGN_OUT",
    COMPLETED_SIGN_OUT: "COMPLETED_SIGN_OUT",
    SIGN_OUT_ERROR: "SIGN_OUT_ERROR",

    REQUEST_AUTH_PROVIDERS: "REQUEST_AUTH_PROVIDERS",
    RECEIVE_AUTH_PROVIDERS: "RECEIVE_AUTH_PROVIDERS",
    RECEIVE_AUTH_PROVIDERS_ERROR: "RECEIVE_AUTH_PROVIDERS_ERROR"
};
