{{- if .Values.global.useAwsRdsDb }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-dev-proxy
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      service: rds-dev-proxy
  template:
    metadata:
      annotations:
      labels:
        service: rds-dev-proxy
    spec:
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      containers:
      - name: rds-dev-proxy
        command:
        - socat
        - "TCP4-LISTEN:5432,fork,reuseaddr"
        - "TCP4:{{ .Values.awsRdsEndpoint | default .Values.global.awsRdsEndpoint | required "global.awsRdsEndpoint or Value.awsRdsEndpoint is required" }}:5432"
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - netstat -an | grep 5432
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - netstat -an | grep 5432
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: {{ include "magda.image" . | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
{{- end }}