{{- if .Values.controlPlaneSecret.create -}}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace .Values.controlPlaneSecret.name) | default dict -}}
{{- if or (empty $existing) (include "magda.isPartOfRelease" (dict "objectData" $existing "root" .)) -}}
{{- $data := (get $existing "data") | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controlPlaneSecret.name }}
  labels:
{{ include "agent-services.installationLabels" . | indent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.controlPlaneSecret.key }}: {{ (get $data .Values.controlPlaneSecret.key) | default (randAlphaNum 48 | b64enc) | quote }}
{{- end -}}
{{- end -}}
