apiVersion: v1
kind: Service
metadata:
  name: agent-manager
  labels:
{{ include "agent-services.installationLabels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: magda-agent-manager
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
