{{- if and .Values.enableTls (not .Values.useDefaultCertificate) }}
{{- $domain := include "magda.getExternalDomain" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: magda-cert
spec:
  secretName: magda-cert-tls
  issuerRef:
    name: {{ .Values.certIssuerName | quote }}
    kind: {{ .Values.certIssuerKind | quote }}
{{- if empty .Values.domains }}
  commonName: {{ $domain | quote }}
{{- else }}
  commonName: {{ index .Values.domains 0 | quote }}
{{- end }}
  dnsNames:
{{- if empty .Values.domains }}
  - {{ $domain | quote }}
{{- else }}
  {{- range .Values.domains }}
  - {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
