version: "3"
services:
  test-es:
    image: data61/elasticsearch:6.8.22
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch.yml:/tmp/elasticsearch.yml
      - ./setup-test.sh:/tmp/setup.sh
      - ./regionSynonyms.test.txt:/tmp/regionSynonyms.txt
      - ./wn_s_test.pl:/tmp/wn_s.pl
    environment:
      - NODE_NAME=es-data-0
      - CLUSTER_NAME=myesdb
      - NODE_DATA=true
      - NODE_MASTER=true
      - NODE_INGEST=true
      - HTTP_ENABLE=true
      - REPO=/data/repo
      - DISCOVERY_SERVICE=localhost
      - NETWORK_HOST=0.0.0.0
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.data=/data/data
      - path.logs=/data/logs
    entrypoint:
      - /tmp/setup.sh
