apiVersion: v1
kind: ConfigMap
metadata:
  name: "indexer-app-conf"
data:
  deploy-application.conf: {{ (mustRegexReplaceAllLiteral "^\\s*{" ((include "magda.indexer.appConfig" .) | fromJson | mustToPrettyJson) "{\n  include \"application\"") | quote }}