apiVersion: v1
kind: Service
metadata:
  name: indexer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 6103
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30103
  type: NodePort
{{- end }}
  selector:
    service: indexer
