image: 
  name: "magda-tenant-api"
  # repository: 
  # tag: 
  # pullPolicy: 
  # pullSecrets: 

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  pullSecrets: false

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 50m

# -- when set to true, auth API will print verbose debug info (e.g. sql statements) to log
debug: false

# -- when set to true, API will not query policy engine for auth decision but assume it's always permitted. 
# It's for debugging only.
skipAuth: false