#!/usr/bin/env bash
# Render manifests/30-sandbox-templates.yaml: one SandboxTemplate + 0-replica
# SandboxWarmPool per (runtime, DSH auth) variant used by #3841:
#   dsh-gvisor-stock  dsh-runc-stock  dsh-gvisor-nba  dsh-runc-nba
# plus dsh-runc-stock-hb120: DSH WebSocket heartbeat raised to 120 s, the
# counterfactual for the ingress idle-timeout test.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
PUBLIC_URL="${PUBLIC_URL:-https://magda.test:18443/api/v0/agent/runtime/}"
TRUSTED_HOSTS="${TRUSTED_HOSTS:-magda.test:18443}"
{
echo "# Generated by scripts/render-sandbox-templates.sh. Do not edit by hand."
for variant in "gvisor stock" "runc stock" "gvisor nba" "runc nba" "runc stock 120000"; do
    read -r runtime auth heartbeat <<<"$variant"
    name="dsh-${runtime}-${auth}${heartbeat:+-hb$((heartbeat / 1000))}"
    runtime_line=""
    [[ "$runtime" == gvisor ]] && runtime_line="      runtimeClassName: gvisor"
    browser_auth=true
    [[ "$auth" == nba ]] && browser_auth=false
    cat <<YAML
---
apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxTemplate
metadata:
  name: ${name}
  namespace: magda-agent-poc
spec:
  # Controller-managed Service per Sandbox (status.serviceFQDN). DSH listens on
  # the Pod network itself, so the Service targets DSH :3080 with no bridge.
  service: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  networkPolicyManagement: Managed
  networkPolicy:
    ingress:
      # Only the Agent Manager proxy may reach DSH; DSH's Host/Origin fence is
      # not an access control against network peers (Host: 127.0.0.1 is trusted).
      - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: magda-agent-manager
        ports:
          - port: 3080
            protocol: TCP
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
            podSelector:
              matchLabels:
                k8s-app: kube-dns
        ports:
          - {port: 53, protocol: UDP}
          - {port: 53, protocol: TCP}
      # PoC stand-in for the Magda LLM Services endpoint (#3838).
      - to:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: mock-llm
        ports:
          - {port: 8080, protocol: TCP}
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 10.0.0.0/8
                - 172.16.0.0/12
                - 192.168.0.0/16
                - 169.254.0.0/16
                - 100.64.0.0/10
  podTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: magda-agent-sandbox
        magda.io/agent-variant: ${name}
    spec:
${runtime_line}
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: agent
          image: magda-agent-dsh:${auth}
          imagePullPolicy: Never
          ports:
            - name: dsh
              containerPort: 3080
          env:
            - {name: DSH_PUBLIC_URL, value: "${PUBLIC_URL}"}
            - {name: DSH_TRUSTED_HOSTS, value: "${TRUSTED_HOSTS}"}
            - {name: DSH_BROWSER_AUTH, value: "${browser_auth}"}
            - {name: MAGDA_LLM_BASE_URL, value: "http://mock-llm.magda-agent-poc.svc.cluster.local/v1"}
            # The mock LLM accepts any key; production uses the bootstrap-written
            # Magda API key (#3825), never a template value.
            - {name: MAGDA_LLM_API_KEY, value: "mock"}
            - {name: DSH_WS_HEARTBEAT_MS, value: "${heartbeat}"}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests: {cpu: 100m, memory: 384Mi, ephemeral-storage: 256Mi}
            limits: {cpu: "1", memory: 1536Mi, ephemeral-storage: 1Gi}
          # Probed by the kubelet from the node over the Pod network: this only
          # passes when DSH listens on the Pod IP (also under gVisor).
          readinessProbe:
            tcpSocket:
              port: 3080
            periodSeconds: 3
            failureThreshold: 60
          volumeMounts:
            - name: data
              mountPath: /data
---
apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: ${name}
  namespace: magda-agent-poc
spec:
  replicas: 0
  sandboxTemplateRef:
    name: ${name}
YAML
done
} > "$HERE/manifests/30-sandbox-templates.yaml"
