apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kibana
  template:
    metadata:
      labels:
        service: kibana
    spec:
      {{- include "magda.imagePullSecrets" (dict "image" .Values.kibanaImage) | indent 6 }}
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        image: {{ include "magda.image" (dict "image" .Values.kibanaImage) | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" (dict "image" .Values.kibanaImage) | quote }}
        name: kibana
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
        ports:
        - containerPort: 5601
