magda:
  magda-core:
    registry-api:
      # turn off schema validation for dev site deployment until we fixed existing connectors schema mismatch issues.
      validateJsonSchema: false

# auth plugin for google
magda-auth-google:
  googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"

magda-auth-internal:
  authPluginConfig:
    loginFormExtraInfoContent: "Forgot your password? Email [magda-test@googlegroups.com](magda-test@googlegroups.com)"

magda-auth-arcgis:
  arcgisClientId: "d0MgVUbbg5Z6vmWo"
  arcgisInstanceBaseUrl: "https://www.arcgis.com"

magda-auth-facebook:
  clientId: "173073926555600"

connector-dga:
  config:
    id: dga
    name: "data.gov.au"
    sourceUrl: "https://data.gov.au/data/"
    pageSize: 100
    ignoreHarvestSources: ["*"]

connector-environment:
  config:
    id: environment
    name: Department of the Environment and Energy
    sourceUrl: http://www.environment.gov.au/fed/csw
    pageSize: 100

connector-dcceew:
  config:
    id: dcceew
    name: "Department of Climate Change, Energy, the Environment and Water"
    sourceUrl: https://fed.dcceew.gov.au/api/feed/dcat-us/1.1.json