magda:
  magda-core:
    registry-api:
      # turn off schema validation for dev site deployment until we fixed existing connectors schema mismatch issues.
      validateJsonSchema: false

# auth plugin for google
magda-auth-google:
  googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"

magda-auth-internal:
  authPluginConfig:
    loginFormExtraInfoContent: "Forgot your password? Email [magda-test@googlegroups.com](magda-test@googlegroups.com)"

magda-auth-arcgis:
  arcgisClientId: "d0MgVUbbg5Z6vmWo"
  arcgisInstanceBaseUrl: "https://www.arcgis.com"

magda-auth-facebook:
  clientId: "173073926555600"

connector-dga:
  config:
    id: dga
    name: "data.gov.au"
    sourceUrl: "https://data.gov.au/data/"
    pageSize: 100
    ignoreHarvestSources: ["*"]

connector-act:
  config:
    id: act
    name: ACT Government data.act.gov.au
    sourceUrl: https://www.data.act.gov.au/data.json

connector-actmapi:
  config:
    id: actmapi
    name: ACT Government ACTMAPi
    sourceUrl: https://actmapi-actgov.opendata.arcgis.com/api/feed/dcat-us/1.1.json

connector-aims:
  config:
    id: aims
    name: Australian Institute of Marine Science
    sourceUrl: https://geonetwork.apps.aims.gov.au/geonetwork/srv/eng/csw
    outputSchema: http://standards.iso.org/iso/19115/-3/mdb/2.0
    typeNames: mdb:MD_Metadata
    pageSize: 100

connector-aodn:
  config:
    id: aodn
    name: Australian Oceans Data Network
    sourceUrl: https://catalogue.aodn.org.au/geonetwork/srv/eng/csw
    outputSchema: http://standards.iso.org/iso/19115/-3/mdb/2.0
    typeNames: mdb:MD_Metadata
    pageSize: 100

connector-bom:
  config:
    id: bom
    name: Bureau of Meteorology
    sourceUrl: http://www.bom.gov.au/geonetwork/srv/eng/csw
    pageSize: 100

connector-aurin:
  config:
    id: aurin
    name: Australian Urban Research Infrastructure Network
    sourceUrl: https://data.aurin.org.au/
    pageSize: 100

connector-brisbane:
  config:
    id: brisbane
    name: Brisbane City Council
    sourceUrl: https://www.data.brisbane.qld.gov.au/data/
    pageSize: 100

connector-hobart:
  config:
    id: hobart
    name: City of Hobart Open Data Portal
    sourceUrl: https://data-1-hobartcc.opendata.arcgis.com/api/feed/dcat-us/1.1.json

connector-marlin:
  config:
    id: marlin
    name: CSIRO Marlin
    sourceUrl: https://marlin.csiro.au/geonetwork/srv/eng/csw
    outputSchema: http://standards.iso.org/iso/19115/-3/mdb/2.0
    typeNames: mdb:MD_Metadata
    pageSize: 50

connector-environment:
  config:
    id: environment
    name: Department of the Environment and Energy
    sourceUrl: http://www.environment.gov.au/fed/csw
    pageSize: 100

connector-ga:
  config:
    id: ga
    name: Geoscience Australia
    sourceUrl: https://ecat.ga.gov.au/geonetwork/srv/eng/csw
    outputSchema: http://standards.iso.org/iso/19115/-3/mdb/1.0
    typeNames: mdb:MD_Metadata
    pageSize: 100

connector-logan:
  config:
    id: logan
    name: Logan City Council
    sourceUrl: https://data-logancity.opendata.arcgis.com/api/feed/dcat-us/1.1.json

connector-melbournewater:
  config:
    id: melbournewater
    name: Melbourne Water Corporation
    sourceUrl: https://data-melbournewater.opendata.arcgis.com/api/feed/dcat-us/1.1.json

connector-melbourne:
  config:
    id: melbourne
    name: Melbourne Data
    sourceUrl: https://data.melbourne.vic.gov.au/data.json

connector-mrt:
  config:
    id: mrt
    name: Mineral Resources Tasmania
    sourceUrl: http://www.mrt.tas.gov.au/web-catalogue/srv/eng/csw
    pageSize: 100

connector-moretonbay:
  config:
    id: moretonbay
    name: Moreton Bay Regional Council Data Portal
    sourceUrl: https://datahub.moretonbay.qld.gov.au/api/feed/dcat-us/1.1.json

connector-neii:
  config:
    id: neii
    name: National Environmental Information Infrastructure
    sourceUrl: http://neii.bom.gov.au/services/catalogue/csw
    pageSize: 100

connector-nsw:
  config:
    id: nsw
    name: New South Wales Government
    sourceUrl: https://data.nsw.gov.au/data/
    pageSize: 100

# Service is not available
# connector-sdinsw:
#   config:
#     id: sdinsw
#     name: NSW Land and Property
#     sourceUrl: https://sdi.nsw.gov.au/csw
#     pageSize: 100

connector-qld:
  config:
    id: qld
    name: Queensland Government
    sourceUrl: https://data.qld.gov.au/
    pageSize: 100

connector-sa:
  config:
    id: sa
    name: South Australia Government
    sourceUrl: https://data.sa.gov.au/data/
    pageSize: 100

connector-listtas:
  config:
    id: listtas
    name: Tasmania TheList
    sourceUrl: https://data.thelist.tas.gov.au:443/datagn/srv/eng/csw
    pageSize: 100

connector-tern:
  config:
    id: tern
    name: Terrestrial Ecosystem Research Network
    sourceUrl: https://geonetwork.tern.org.au/geonetwork/srv/eng/csw
    outputSchema: http://standards.iso.org/iso/19115/-3/mdb/2.0
    typeNames: mdb:MD_Metadata
    pageSize: 100

connector-vic:
  config:
    id: vic
    name: Victoria Government
    sourceUrl: https://discover.data.vic.gov.au/
    pageSize: 100
    ignoreHarvestSources: []
    presetRecordAspects:
    - id: organization-details
      recordType: Organization
      data: 
        title: "Victoria Government"
        jurisdiction: "Victoria Government"


connector-wa:
  config:
    id: wa
    name: Western Australia Government
    sourceUrl: https://catalogue.data.wa.gov.au/
    pageSize: 25
    customJsFilterCode: |
      if(type === "Dataset") {
        return jsonData["access_level"]=="open" ? true : false;
      } else {
        return true;
      }

connector-dap:
  config:
    id: dap
    name: CSIRO
    sourceUrl: https://data.csiro.au/dap/ws/v2/
    pageSize: 100

connector-vic-cardinia:
  config:
    id: vic-cardinia
    name: Cardinia Shire Council
    sourceUrl: https://data-cscgis.opendata.arcgis.com/api/feed/dcat-us/1.1.json

connector-nt-darwin:
  config:
    id: nt-darwin
    name: City of Darwin
    sourceUrl: https://open-darwin.opendata.arcgis.com/api/feed/dcat-us/1.1.json

connector-southern-grampians:
  config:
    id: southern-grampians
    name: Southern Grampians Shire Council
    sourceUrl: https://www.connectgh.com.au/data.json

connector-gbrmpa:
  config:
    id: gbrmpa
    name: GBRMPA Geoportal
    sourceUrl: https://geoportal.gbrmpa.gov.au/api/feed/dcat-us/1.1.json

connector-launceston:
  config:
    id: launceston
    name: City of Launceston Open Data
    sourceUrl: https://opendata.launceston.tas.gov.au/api/feed/dcat-us/1.1.json