{{- if .Values.autoCreateAuthSecrets }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "auth-secrets") | default dict }}
{{- /* only attempt to create secret when secret not exists or the existing secret is part of current helm release */}}
{{- if or (empty $secret) (include "magda.isPartOfRelease" (dict "objectData" $secret "root" .) | empty | not) }}
{{- $secretData := (get $secret "data") | default dict }}
{{- $jwtSecret := (get $secretData "jwt-secret") | default (randAlphaNum 32 | b64enc) }}
{{- $sessionSecret := (get $secretData "session-secret") | default (randAlphaNum 32 | b64enc) }}
apiVersion: v1
kind: Secret
metadata:
  name: "auth-secrets"
  annotations:
    "helm.sh/resource-policy": keep
{{- $openfaasConfig := (get .Values.global "openfaas") | default dict }}
{{- $openfaasSecretsConfig := (get $openfaasConfig "secrets") | default dict }}
{{- $openfaasAuthSecretsConfig := (get $openfaasSecretsConfig "authSecrets") | default false }}
{{- $openfaasNamespacePrefix :=  (get $openfaasConfig "namespacePrefix") | default .Release.Namespace }}
{{- $openfaasFunctionNamespace := (get $openfaasConfig "functionNamespace") | default "openfaas-fn" }}
{{- if $openfaasAuthSecretsConfig }}
    "replicator.v1.mittwald.de/replication-allowed": "true"
    "replicator.v1.mittwald.de/replication-allowed-namespaces": {{ printf "%s-%s" $openfaasNamespacePrefix $openfaasFunctionNamespace | quote }}
{{- end }}
type: Opaque
data:
  jwt-secret: {{ $jwtSecret | quote }}
  session-secret: {{ $sessionSecret | quote }}
{{- end }}
{{- end }}