apiVersion: apps/v1
kind: Deployment
metadata:
  name: correspondence-api
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: correspondence-api
  template:
    metadata:
      labels:
        service: correspondence-api
    spec:
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      containers:
      - name: correspondence-api
        image: {{ include "magda.image" . | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
        command: [
            "node",
            "/usr/src/app/component/dist/index.js",
            "--listenPort", "80",
            "--registryUrl", "http://registry-api/v0",
            "--contentApiUrl", "http://content-api/v0",
            "--externalUrl", {{ .Values.global.externalUrl | quote }},
            "--smtpHostname", {{ .Values.smtpHostname | quote }},
            "--smtpPort", {{ .Values.smtpPort | default 587 | quote }},
            "--smtpSecure", {{ .Values.smtpSecure | default true | quote }},
            {{- if .Values.global.defaultContactEmail }}
            "--defaultRecipient", {{ .Values.global.defaultContactEmail | quote }},
            {{- else }}
            "--defaultRecipient", {{ .Values.defaultRecipient | quote }},
            {{- end }}
            "--alwaysSendToDefaultRecipient", {{.Values.alwaysSendToDefaultRecipient | quote}}
        ]
        livenessProbe:
          httpGet:
            path: /v0/status/live
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /v0/status/ready
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_ENV
          value: production
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: password
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
