UPDATE public.content SET id='lang/en/global/appName' WHERE id='lang/en/appName';
INSERT INTO public.content VALUES ('lang/en/global/appName', 'text/plain', 'Magda') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/publishersPage/publishersBreadCrumb', 'text/plain', 'Organisations') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/publishersPage/publishersPageTitle', 'text/plain', 'Organisations') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/publishersPage/publishersSearchPlaceholder', 'text/plain', 'Search for Organisations') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/publisherPage/publishersBreadCrumb', 'text/plain', 'Organisations') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/publisherPage/publisherNotFoundMessage', 'text/plain', 'Organisation cannot be found') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/publishersPage/noPublishersMatchSearchMessage', 'text/plain', 'Sorry, we couldn''t find any organisations that match your search.') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/publisherPage/publisherHasNoDescMessage', 'text/plain', 'This publisher has no description') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/datasetSuggestForm/suggestSuccessMessage', 'text/plain', 'Someone from the the organisation that handles the relevant data or this website will get in touch soon. Please note that the time taken to action your request may vary depending on the nature of the request.') ON CONFLICT DO NOTHING;
INSERT INTO public.content VALUES ('lang/en/searchDatasetsPage/publisherFilterTitle', 'text/plain', 'Organisation') ON CONFLICT DO NOTHING;