apiVersion: v1
kind: Service
metadata:
  name: "{{ template "magda.opensearch.data.fullname" . }}-headless"
  labels:
    {{- include "magda.common.labels.standard" . | nindent 4 }}
    component: {{ .Values.clusterName | quote }}
    role: data
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "magda.common.labels.matchLabels" . | nindent 4 }}
    component: {{ .Values.clusterName | quote }}
    role: data
  ports:
  - name: http
    port: {{ .Values.httpPort }}
    protocol: TCP
  - name: transport
    port: {{ .Values.transportPort }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.metricsPort }}
