#!/usr/bin/env bash
# Render gke/manifests/poc.yaml for the #3848 GKE qualification: the #3841
# mock LLM, Agent Manager PoC proxy and DSH SandboxTemplates, adapted for GKE:
#   - images from Artifact Registry (IfNotPresent), not `imagePullPolicy: Never`;
#   - the external authority is the LoadBalancer's <ip>.sslip.io name on :443;
#   - ingress-nginx stands in for magda-gateway: one Ingress routes
#     /api/v0/agent/runtime/* to Agent Manager (/runtime/*). The client mints
#     the X-Magda-Session JWT itself (no Magda auth stack is deployed);
#   - templates: dsh-gvisor (GKE Sandbox node pool), dsh-runc (default pool,
#     control) and, for the idle-timeout tests, dsh-gvisor-hb120 / -hb3600
#     (DSH WebSocket heartbeat raised to 120 s / 1 h, i.e. a quiet socket).
#     All WarmPool 0.
# Usage: EXTERNAL_HOST=<host> scripts/render-manifests.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
source "$HERE/env.sh"
EXTERNAL_HOST="${EXTERNAL_HOST:?EXTERNAL_HOST (e.g. 34-87-194-9.sslip.io)}"
PUBLIC_URL="https://${EXTERNAL_HOST}/api/v0/agent/runtime/"
WS_TIMEOUT="${WS_TIMEOUT:-}"   # empty = ingress-nginx default (60 s)
{
echo "# Generated by gke/scripts/render-manifests.sh. Do not edit by hand."
cat <<YAML
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-llm
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels: {app.kubernetes.io/name: mock-llm}
  template:
    metadata:
      labels: {app.kubernetes.io/name: mock-llm}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mock-llm
          image: ${TOOLS_IMAGE}
          imagePullPolicy: IfNotPresent
          command: ["node", "mock-llm/server.mjs"]
          ports: [{containerPort: 8080}]
          resources:
            requests: {cpu: 10m, memory: 32Mi}
            limits: {cpu: 200m, memory: 128Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: mock-llm
  namespace: ${NS}
spec:
  selector: {app.kubernetes.io/name: mock-llm}
  ports: [{port: 80, targetPort: 8080}]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-manager
  namespace: ${NS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-manager
  namespace: ${NS}
rules:
  - apiGroups: ["extensions.agents.x-k8s.io"]
    resources: ["sandboxclaims"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-manager
  namespace: ${NS}
subjects:
  - kind: ServiceAccount
    name: agent-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-manager
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels: {app.kubernetes.io/name: magda-agent-manager}
  template:
    metadata:
      labels: {app.kubernetes.io/name: magda-agent-manager}
    spec:
      serviceAccountName: agent-manager
      containers:
        - name: agent-manager
          image: ${TOOLS_IMAGE}
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 8080}]
          env:
            - {name: AUTH_MODE, value: managed-cookie}
            - {name: EXTERNAL_AUTHORITY, value: "${EXTERNAL_HOST}"}
            - {name: MOUNT_PATH, value: "/api/v0/agent/runtime/"}
            - {name: PATH_PREFIX, value: "/runtime"}
            - {name: SANDBOX_NAMESPACE, value: "${NS}"}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: {name: auth-secrets, key: jwt-secret}
          readinessProbe:
            httpGet: {path: /healthz, port: 8080}
          resources:
            requests: {cpu: 20m, memory: 48Mi}
            limits: {cpu: 500m, memory: 256Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: agent-manager
  namespace: ${NS}
spec:
  selector: {app.kubernetes.io/name: magda-agent-manager}
  ports: [{port: 80, targetPort: 8080}]
---
# In production only magda-gateway may call Agent Manager; here ingress-nginx
# stands in for the gateway. NOTE: this cluster does not enforce NetworkPolicy
# (see tests/netpol-gke.sh), so this object documents intent only.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agent-manager-ingress
  namespace: ${NS}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: magda-agent-manager}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: ${INGRESS_NS}}
          podSelector:
            matchLabels: {app.kubernetes.io/component: controller}
      ports: [{port: 8080, protocol: TCP}]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agent-runtime
  namespace: ${NS}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /runtime/\$2
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
YAML
if [[ -n "$WS_TIMEOUT" ]]; then
cat <<YAML
    nginx.ingress.kubernetes.io/proxy-read-timeout: "${WS_TIMEOUT}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "${WS_TIMEOUT}"
YAML
fi
cat <<YAML
spec:
  ingressClassName: ${INGRESS_CLASS}
  tls:
    - hosts: ["${EXTERNAL_HOST}"]
      secretName: poc-tls
  rules:
    - host: ${EXTERNAL_HOST}
      http:
        paths:
          - path: /api/v0/agent/runtime(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: agent-manager
                port: {number: 80}
YAML
for variant in "gvisor" "runc" "gvisor 120000" "gvisor 3600000"; do
    read -r runtime heartbeat <<<"$variant"
    name="dsh-${runtime}${heartbeat:+-hb$((heartbeat / 1000))}"
    runtime_line=""
    [[ "$runtime" == gvisor ]] && runtime_line="      runtimeClassName: gvisor"
cat <<YAML
---
apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxTemplate
metadata:
  name: ${name}
  namespace: ${NS}
spec:
  service: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        # default StorageClass (standard-rwo: pd.csi.storage.gke.io, pd-balanced)
        resources:
          requests:
            storage: 1Gi
  networkPolicyManagement: Managed
  networkPolicy:
    ingress:
      - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: magda-agent-manager
        ports:
          - port: 3080
            protocol: TCP
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
            podSelector:
              matchLabels:
                k8s-app: kube-dns
        ports:
          - {port: 53, protocol: UDP}
          - {port: 53, protocol: TCP}
      - to:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: mock-llm
        ports:
          - {port: 8080, protocol: TCP}
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 10.0.0.0/8
                - 172.16.0.0/12
                - 192.168.0.0/16
                - 169.254.0.0/16
                - 100.64.0.0/10
  podTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: magda-agent-sandbox
        magda.io/agent-variant: ${name}
    spec:
${runtime_line}
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        # Required on CSI block volumes (GKE PD): with the default policy
        # (Always) the kubelet re-applies fsGroup recursively on every mount and
        # widens DSH's 0600 .credentials.yaml to 0660, and DSH then refuses to
        # start after a resume or Pod replacement (#3848). hostPath-backed
        # Minikube volumes skip fsGroup handling, which hid this in #3841.
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: agent
          image: ${DSH_IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - name: dsh
              containerPort: 3080
          env:
            - {name: DSH_PUBLIC_URL, value: "${PUBLIC_URL}"}
            - {name: DSH_TRUSTED_HOSTS, value: "${EXTERNAL_HOST}"}
            - {name: DSH_BROWSER_AUTH, value: "true"}
            - {name: MAGDA_LLM_BASE_URL, value: "http://mock-llm.${NS}.svc.cluster.local/v1"}
            - {name: MAGDA_LLM_API_KEY, value: "mock"}
            - {name: DSH_WS_HEARTBEAT_MS, value: "${heartbeat}"}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests: {cpu: 100m, memory: 384Mi, ephemeral-storage: 256Mi}
            limits: {cpu: "1", memory: 1536Mi, ephemeral-storage: 1Gi}
          readinessProbe:
            tcpSocket:
              port: 3080
            periodSeconds: 3
            failureThreshold: 60
          volumeMounts:
            - name: data
              mountPath: /data
            - name: run
              mountPath: /run/magda-agent
      volumes:
        - name: run
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
---
apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: ${name}
  namespace: ${NS}
spec:
  replicas: ${REPLICAS:-0}
  sandboxTemplateRef:
    name: ${name}
YAML
done
} > "$HERE/manifests/poc.yaml"
echo "rendered $HERE/manifests/poc.yaml for https://${EXTERNAL_HOST}/"
