/* JS */ gapi.loaded_0(function(_){var window=this;
var ea,ta,ua,wa,Aa,Da,Ba,Fa,Ha,Ia;_.ca=function(a){return function(){return _.aa[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.aa=[];_.da="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var ha;a:{var oa={a:!0},pa={};try{pa.__proto__=oa;ha=pa.a;break a}catch(a){}ha=!1}ea=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}_.qa=ea;ta="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
ua="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this;wa=function(){wa=function(){};ua.Symbol||(ua.Symbol=Aa)};Aa=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();Da=function(){wa();var a=ua.Symbol.iterator;a||(a=ua.Symbol.iterator=ua.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ta(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Ba(this)}});Da=function(){}};
Ba=function(a){var b=0;return Fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};Fa=function(a){Da();a={next:a};a[ua.Symbol.iterator]=function(){return this};return a};_.Ga=function(a){Da();var b=a[window.Symbol.iterator];return b?b.call(a):Ba(a)};Ha=function(a,b){if(b){var c=ua;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ta(c,a,{configurable:!0,writable:!0,value:b})}};
Ia=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
Ha("WeakMap",function(a){function b(a){Ia(a,d)||ta(a,d,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d["delete"](b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(n){return!1}}())return a;var d="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");c("seal");var e=0,f=function(a){this.ya=
(e+=Math.random()+1).toString();if(a){wa();Da();a=_.Ga(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,c){b(a);if(!Ia(a,d))throw Error("a`"+a);a[d][this.ya]=c;return this};f.prototype.get=function(a){return Ia(a,d)?a[d][this.ya]:void 0};f.prototype.has=function(a){return Ia(a,d)&&Ia(a[d],this.ya)};f.prototype["delete"]=function(a){return Ia(a,d)&&Ia(a[d],this.ya)?delete a[d][this.ya]:!1};return f});
Ha("Map",function(a){if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(_.Ga([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(q){return!1}}())return a;wa();Da();var b=new window.WeakMap,c=function(a){this.Ee={};this.Me=
f();this.size=0;if(a){a=_.Ga(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.Ee[c.id]=[]);c.fe?c.fe.value=b:(c.fe={next:this.Me,Gi:this.Me.Gi,head:this.Me,key:a,value:b},c.list.push(c.fe),this.Me.Gi.next=c.fe,this.Me.Gi=c.fe,this.size++);return this};c.prototype["delete"]=function(a){a=d(this,a);return a.fe&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.Ee[a.id],a.fe.Gi.next=a.fe.next,a.fe.next.Gi=a.fe.Gi,
a.fe.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.Ee={};this.Me=this.Me.Gi=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).fe};c.prototype.get=function(a){return(a=d(this,a).fe)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),
d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[window.Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++h,b.set(c,d)):d="p_"+c;var e=a.Ee[d];if(e&&Ia(a.Ee,d))for(a=0;a<e.length;a++){var f=e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,fe:f}}return{id:d,list:e,index:-1,fe:void 0}},e=function(a,b){var c=a.Me;return Fa(function(){if(c){for(;c.head!=a.Me;)c=c.Gi;for(;c.next!=c.head;)return c=
c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.Gi=a.next=a.head=a},h=0;return c});_.Ja=_.Ja||{};_.m=this;_.r=function(a){return void 0!==a};_.v=function(a){return"string"==typeof a};
_.Ka=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.La=function(a){return"array"==_.Ka(a)};_.Ma="closure_uid_"+(1E9*Math.random()>>>0);_.Na=Date.now||function(){return+new Date};_.w=function(a,b){a=a.split(".");var c=_.m;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.r(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}};
_.z=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Eo=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.Ra=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage",loggingUrl:"https://accounts.google.com/o/oauth2/client_log"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},
card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},appfinder:{url:"https://gsuite.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,
"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0}});

var ab,eb,fb;_.Sa=function(a,b){return _.aa[a]=b};_.Ua=function(a){return"number"==typeof a};_.Va=function(){};_.Wa=function(a){var b=_.Ka(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Za=function(a){return"function"==_.Ka(a)};_.$a=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};ab=0;_.bb=function(a){return a[_.Ma]||(a[_.Ma]=++ab)};eb=function(a,b,c){return a.call.apply(a.bind,arguments)};
fb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.B=function(a,b,c){_.B=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?eb:fb;return _.B.apply(null,arguments)};
var ib;_.kb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(_.v(a))return _.v(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.lb=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if(_.v(a))return _.v(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
_.mb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};_.nb=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=_.v(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};
_.pb=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=_.v(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};_.qb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.v(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
_.sb=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.v(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.tb=function(a,b){return 0<=(0,_.kb)(a,b)};_.ub=function(a){return Array.prototype.concat.apply([],arguments)};_.wb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Bb,Cb,Db,Eb,Ib,Jb,Ab,Ob;_.xb=function(a,b){return 0==a.lastIndexOf(b,0)};_.yb=function(a){return/^[\s\xa0]*$/.test(a)};_.zb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.Kb=function(a){if(!Ab.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Bb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Cb,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Db,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Eb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ib,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Jb,"&#0;"));return a};Bb=/&/g;Cb=/</g;Db=/>/g;Eb=/"/g;Ib=/'/g;Jb=/\x00/g;Ab=/[\x00&<>"']/;_.Nb=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Pb=function(a,b){var c=0;a=(0,_.zb)(String(a)).split(".");b=(0,_.zb)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=Ob(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||Ob(0==f[2].length,0==h[2].length)||Ob(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; Ob=function(a,b){return a<b?-1:a>b?1:0};_.Qb=2147483648*Math.random()|0;_.Rb=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
a:{var Tb=_.m.navigator;if(Tb){var Ub=Tb.userAgent;if(Ub){_.Sb=Ub;break a}}_.Sb=""}_.Vb=function(a){return-1!=_.Sb.indexOf(a)};var $b;_.Wb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.Xb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Yb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.Zb=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};$b="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.ac=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<$b.length;f++)c=$b[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.bc=function(){return _.Vb("Opera")};_.cc=function(){return _.Vb("Trident")||_.Vb("MSIE")};_.dc=function(){return _.Vb("iPhone")&&!_.Vb("iPod")&&!_.Vb("iPad")};_.ec=function(){return _.dc()||_.Vb("iPad")||_.Vb("iPod")};var fc=function(a){fc[" "](a);return a},ic;fc[" "]=_.Va;_.gc=function(a,b){try{return fc(a[b]),!0}catch(c){}return!1};ic=function(a,b){var c=hc;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var yc,zc,hc,Hc;_.jc=_.bc();_.C=_.cc();_.kc=_.Vb("Edge");_.lc=_.kc||_.C;_.mc=_.Vb("Gecko")&&!(-1!=_.Sb.toLowerCase().indexOf("webkit")&&!_.Vb("Edge"))&&!(_.Vb("Trident")||_.Vb("MSIE"))&&!_.Vb("Edge");_.nc=-1!=_.Sb.toLowerCase().indexOf("webkit")&&!_.Vb("Edge");_.oc=_.nc&&_.Vb("Mobile");_.pc=_.Vb("Macintosh");_.qc=_.Vb("Windows");_.rc=_.Vb("Linux")||_.Vb("CrOS");_.sc=_.Vb("Android");_.tc=_.dc();_.vc=_.Vb("iPad");_.wc=_.Vb("iPod");_.xc=_.ec();
yc=function(){var a=_.m.document;return a?a.documentMode:void 0};a:{var Ac="",Bc=function(){var a=_.Sb;if(_.mc)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.kc)return/Edge\/([\d\.]+)/.exec(a);if(_.C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.nc)return/WebKit\/(\S+)/.exec(a);if(_.jc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Bc&&(Ac=Bc?Bc[1]:"");if(_.C){var Cc=yc();if(null!=Cc&&Cc>(0,window.parseFloat)(Ac)){zc=String(Cc);break a}}zc=Ac}_.Dc=zc;hc={}; _.Ec=function(a){return ic(a,function(){return 0<=_.Pb(_.Dc,a)})};_.Gc=function(a){return Number(_.Fc)>=a};var Ic=_.m.document;Hc=Ic&&_.C?yc()||("CSS1Compat"==Ic.compatMode?(0,window.parseInt)(_.Dc,10):5):void 0;_.Fc=Hc;
var Jc,Kc;Jc=!_.C||_.Gc(9);Kc=!_.mc&&!_.C||_.C&&_.Gc(9)||_.mc&&_.Ec("1.9.1");_.Lc=_.C&&!_.Ec("9");_.Mc=_.C||_.jc||_.nc;_.Nc=_.C&&!_.Gc(9);var Oc;_.Pc=function(){this.Bv="";this.SN=Oc};_.Pc.prototype.wh=!0;_.Pc.prototype.Sf=function(){return this.Bv};_.Pc.prototype.toString=function(){return"Const{"+this.Bv+"}"};_.Qc=function(a){return a instanceof _.Pc&&a.constructor===_.Pc&&a.SN===Oc?a.Bv:"type_error:Const"};Oc={};_.Rc=function(a){var b=new _.Pc;b.Bv=a;return b};_.Rc("");
var Tc;_.Uc=function(){this.aB="";this.cO=Tc};_.Uc.prototype.wh=!0;_.Uc.prototype.Sf=function(){return this.aB};_.Uc.prototype.Ez=!0;_.Uc.prototype.Ok=function(){return 1};_.Vc=function(a){if(a instanceof _.Uc&&a.constructor===_.Uc&&a.cO===Tc)return a.aB;_.Ka(a);return"type_error:TrustedResourceUrl"};_.Xc=function(a){return _.Wc(_.Qc(a))};Tc={};_.Wc=function(a){var b=new _.Uc;b.aB=a;return b};
var ad,Yc,cd;_.Zc=function(){this.Fl="";this.LN=Yc};_.Zc.prototype.wh=!0;_.Zc.prototype.Sf=function(){return this.Fl};_.Zc.prototype.Ez=!0;_.Zc.prototype.Ok=function(){return 1};_.$c=function(a){if(a instanceof _.Zc&&a.constructor===_.Zc&&a.LN===Yc)return a.Fl;_.Ka(a);return"type_error:SafeUrl"};ad=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;_.dd=function(a){if(a instanceof _.Zc)return a;a=a.wh?a.Sf():String(a);ad.test(a)||(a="about:invalid#zClosurez");return cd(a)}; _.ed=function(a){if(a instanceof _.Zc)return a;a=a.wh?a.Sf():String(a);ad.test(a)||(a="about:invalid#zClosurez");return cd(a)};Yc={};cd=function(a){var b=new _.Zc;b.Fl=a;return b};cd("about:blank");
var id,jd,nd,md,ld,od;_.gd=function(){this.$A="";this.KN=fd};_.gd.prototype.wh=!0;var fd={};_.gd.prototype.Sf=function(){return this.$A};_.hd=function(a){if(a instanceof _.gd&&a.constructor===_.gd&&a.KN===fd)return a.$A;_.Ka(a);return"type_error:SafeStyle"};_.gd.prototype.wi=function(a){this.$A=a;return this};id=(new _.gd).wi("");
_.kd=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("f`"+c);var d=a[c];null!=d&&(d=_.La(d)?(0,_.pb)(d,jd).join(" "):jd(d),b+=c+":"+d+";")}return b?(new _.gd).wi(b):id};
jd=function(a){if(a instanceof _.Zc)a='url("'+_.$c(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';else if(a instanceof _.Pc)a=_.Qc(a);else{a=String(a);var b=a.replace(ld,"$1").replace(md,"url");if(b=nd.test(b)){for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}b=b&&c}a=b?od(a):"zClosurez"}return a};nd=/^[-,."'%_!# a-zA-Z0-9]+$/;md=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g;ld=/\b(hsl|hsla|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?)\([-0-9a-z.%, ]+\)/g; od=function(a){return a.replace(md,function(a,c,d,e){var b="";d=d.replace(/^(['"])(.*)\1$/,function(a,c,d){b=c;return d});a=_.dd(d).Sf();return c+b+a+b+e})};
_.qd=function(){this.ZA="";this.JN=_.pd};_.qd.prototype.wh=!0;_.pd={};_.td=function(a){a=_.Qc(a);return 0===a.length?rd:(new _.qd).wi(a)};_.qd.prototype.Sf=function(){return this.ZA};_.qd.prototype.wi=function(a){this.ZA=a;return this};var rd=(new _.qd).wi("");
var ud;_.vd=function(){this.Fl="";this.IN=ud;this.pF=null};_.vd.prototype.Ez=!0;_.vd.prototype.Ok=function(){return this.pF};_.vd.prototype.wh=!0;_.vd.prototype.Sf=function(){return this.Fl};_.wd=function(a){if(a instanceof _.vd&&a.constructor===_.vd&&a.IN===ud)return a.Fl;_.Ka(a);return"type_error:SafeHtml"};ud={};_.xd=function(a,b){return(new _.vd).wi(a,b)};_.vd.prototype.wi=function(a,b){this.Fl=a;this.pF=b;return this};_.xd("<!DOCTYPE html>",0);_.yd=_.xd("",0);_.zd=_.xd("<br>",0);
_.Ad=function(a,b){b=b instanceof _.Zc?b:_.ed(b);a.href=_.$c(b)};var Hd,Jd,Ld;_.Fd=function(a){return a?new _.Bd(_.Ed(a)):ib||(ib=new _.Bd)};
_.Gd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.tb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Id=function(a,b){_.Wb(b,function(b,d){b&&b.wh&&(b=b.Sf());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Hd.hasOwnProperty(d)?a.setAttribute(Hd[d],b):_.xb(d,"aria-")||_.xb(d,"data-")?a.setAttribute(d,b):a[d]=b})};Hd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Kd=function(a,b){var c=String(b[0]),d=b[1];if(!Jc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',_.Kb(d.name),'"');if(d.type){c.push(' type="',_.Kb(d.type),'"');var e={};_.ac(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(_.v(d)?c.className=d:_.La(d)?c.className=d.join(" "):_.Id(c,d));2<b.length&&Jd(a,c,b,2);return c};
Jd=function(a,b,c,d){function e(c){c&&b.appendChild(_.v(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!_.Wa(f)||_.$a(f)&&0<f.nodeType?e(f):(0,_.mb)(Ld(f)?_.wb(f):f,e)}};_.Md=function(a){return window.document.createElement(String(a))};_.Nd=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.Od=function(a,b){Jd(_.Ed(a),a,arguments,1)};_.Pd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Qd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.Sd=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.Td=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return _.Sd(a)}};
_.Ud=function(a){return Kc&&void 0!=a.children?a.children:(0,_.nb)(a.childNodes,function(a){return 1==a.nodeType})};_.Vd=function(a){return _.$a(a)&&1==a.nodeType};_.Wd=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Ed=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
Ld=function(a){if(a&&"number"==typeof a.length){if(_.$a(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.Za(a))return"function"==typeof a.item}return!1};_.Bd=function(a){this.Wa=a||_.m.document||window.document};_.g=_.Bd.prototype;_.g.Ca=_.Fd;_.g.UB=_.ca(0);_.g.mb=function(){return this.Wa};_.g.S=_.ca(1);_.g.getElementsByTagName=function(a,b){return(b||this.Wa).getElementsByTagName(String(a))};_.g.ma=function(a,b,c){return _.Kd(this.Wa,arguments)};_.g.createElement=function(a){return this.Wa.createElement(String(a))};
_.g.createTextNode=function(a){return this.Wa.createTextNode(String(a))};_.g.tb=function(){var a=this.Wa;return a.parentWindow||a.defaultView};_.g.appendChild=function(a,b){a.appendChild(b)};_.g.append=_.Od;_.g.canHaveChildren=_.Nd;_.g.xf=_.Pd;_.g.BH=_.Qd;_.g.removeNode=_.Sd;_.g.gQ=_.Td;_.g.Ys=_.Ud;_.g.isElement=_.Vd;_.g.contains=_.Wd;_.g.yh=_.ca(2);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.Xd=window;_.Yd=window.document;_.Zd=_.Xd.location;_.$d=/\[native code\]/;_.ae=function(a,b,c){return a[b]=a[b]||c};_.G=function(){var a;if((a=Object.create)&&_.$d.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.be=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.ce=function(a,b){a=a||{};for(var c in a)_.be(a,c)&&(b[c]=a[c])};_.de=_.ae(_.Xd,"gapi",{});
_.ee=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.fe=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);
_.ge=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");_.he=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.me=function(a,b,c){_.ie(a,b,c,"add","at")};_.ie=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.ne=_.ae(_.Xd,"___jsl",_.G());_.ae(_.ne,"I",0);_.ae(_.ne,"hel",10);var oe,pe,qe,re,se,te,ue;oe=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};pe=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};qe=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
re=function(a,b,c){if(b&&"object"===typeof b)for(var d in b)!Object.prototype.hasOwnProperty.call(b,d)||c&&"___goc"===d&&"undefined"===typeof b[d]||(a[d]&&b[d]&&"object"===typeof a[d]&&"object"===typeof b[d]&&!qe(a[d])&&!qe(b[d])?re(a[d],b[d]):b[d]&&"object"===typeof b[d]?(a[d]=qe(b[d])?[]:{},re(a[d],b[d])):a[d]=b[d])};
se=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);try{var b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
te=function(a,b){var c={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&"undefined"===typeof a[a.length-1].___goc&&(c=a.pop());re(c,b);a.push(c)};
ue=function(a){pe(!0);var b=window.___gcfg,c=oe("cu"),d=window.___gu;b&&b!==d&&(te(c,b),window.___gu=b);b=oe("cu");var e=window.document.scripts||window.document.getElementsByTagName("script")||[];d=[];var f=[];f.push.apply(f,oe("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",!0),
(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=se(f))&&b.push(f));a&&te(c,a);d=oe("cd");a=0;for(b=d.length;a<b;++a)re(pe(),d[a],!0);d=oe("ci");a=0;for(b=d.length;a<b;++a)re(pe(),d[a],!0);a=0;for(b=c.length;a<b;++a)re(pe(),c[a],!0)};_.I=function(a,b){var c=pe();if(!a)return c;a=a.split("/");for(var d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b}; _.ve=function(a,b){var c;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e){var h={};d=d[a[e]]=h}d[a[e]]=b}else c=a;ue(c)};
var we=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.ae(_.ne,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};we&&we();ue();_.w("gapi.config.get",_.I);_.w("gapi.config.update",_.ve);
_.xe=function(a,b){var c=b||window.document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=window.document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(""+(a?"."+a:"")):_.Gd(c,"*",a,b)[0]||null}return a||null};

var Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,mf,nf;Ge=void 0;He=function(a){try{return _.m.JSON.parse.call(_.m.JSON,a)}catch(b){return!1}};Ie=function(a){return Object.prototype.toString.call(a)};Je=Ie(0);Ke=Ie(new Date(0));Le=Ie(!0);Me=Ie("");Ne=Ie({});Pe=Ie([]);
Qe=function(a,b){if(b)for(var c=0,d=b.length;c<d;++c)if(a===b[c])throw new TypeError("Converting circular structure to JSON");d=typeof a;if("undefined"!==d){c=Array.prototype.slice.call(b||[],0);c[c.length]=a;b=[];var e=Ie(a);if(null!=a&&"function"===typeof a.toJSON&&(Object.prototype.hasOwnProperty.call(a,"toJSON")||(e!==Pe||a.constructor!==Array&&a.constructor!==Object)&&(e!==Ne||a.constructor!==Array&&a.constructor!==Object)&&e!==Me&&e!==Je&&e!==Le&&e!==Ke))return Qe(a.toJSON.call(a),c);if(null==
a)b[b.length]="null";else if(e===Je)a=Number(a),(0,window.isNaN)(a)||(0,window.isNaN)(a-a)?a="null":-0===a&&0>1/a&&(a="-0"),b[b.length]=String(a);else if(e===Le)b[b.length]=String(!!Number(a));else{if(e===Ke)return Qe(a.toISOString.call(a),c);if(e===Pe&&Ie(a.length)===Je){b[b.length]="[";var f=0;for(d=Number(a.length)>>0;f<d;++f)f&&(b[b.length]=","),b[b.length]=Qe(a[f],c)||"null";b[b.length]="]"}else if(e==Me&&Ie(a.length)===Je){b[b.length]='"';f=0;for(c=Number(a.length)>>0;f<c;++f)d=String.prototype.charAt.call(a,
f),e=String.prototype.charCodeAt.call(a,f),b[b.length]="\b"===d?"\\b":"\f"===d?"\\f":"\n"===d?"\\n":"\r"===d?"\\r":"\t"===d?"\\t":"\\"===d||'"'===d?"\\"+d:31>=e?"\\u"+(e+65536).toString(16).substr(1):32<=e&&65535>=e?d:"\ufffd";b[b.length]='"'}else if("object"===d){b[b.length]="{";d=0;for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(e=Qe(a[f],c),void 0!==e&&(d++&&(b[b.length]=","),b[b.length]=Qe(f),b[b.length]=":",b[b.length]=e));b[b.length]="}"}else return}return b.join("")}};Re=/[\0-\x07\x0b\x0e-\x1f]/;
Se=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*[\0-\x1f]/;Te=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\[^\\\/"bfnrtu]/;Ue=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\u([0-9a-fA-F]{0,3}[^0-9a-fA-F])/;Ve=/"([^\0-\x1f\\"]|\\[\\\/"bfnrt]|\\u[0-9a-fA-F]{4})*"/g;We=/-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][-+]?[0-9]+)?/g;Xe=/[ \t\n\r]+/g;Ye=/[^"]:/;Ze=/""/g;$e=/true|false|null/g;af=/00/;bf=/[\{]([^0\}]|0[^:])/;cf=/(^|\[)[,:]|[,:](\]|\}|[,:]|$)/;df=/[^\[,:][\[\{]/;ef=/^(\{|\}|\[|\]|,|:|0)+/;ff=/\u2028/g;
gf=/\u2029/g;
hf=function(a){a=String(a);if(Re.test(a)||Se.test(a)||Te.test(a)||Ue.test(a))return!1;var b=a.replace(Ve,'""');b=b.replace(We,"0");b=b.replace(Xe,"");if(Ye.test(b))return!1;b=b.replace(Ze,"0");b=b.replace($e,"0");if(af.test(b)||bf.test(b)||cf.test(b)||df.test(b)||!b||(b=b.replace(ef,"")))return!1;a=a.replace(ff,"\\u2028").replace(gf,"\\u2029");b=void 0;try{b=Ge?[He(a)]:eval("(function (var_args) {\n  return Array.prototype.slice.call(arguments, 0);\n})(\n"+a+"\n)")}catch(c){return!1}return b&&1===
b.length?b[0]:!1};jf=function(){var a=((_.m.document||{}).scripts||[]).length;if((void 0===Ee||void 0===Ge||Fe!==a)&&-1!==Fe){Ee=Ge=!1;Fe=-1;try{try{Ge=!!_.m.JSON&&'{"a":[3,true,"1970-01-01T00:00:00.000Z"]}'===_.m.JSON.stringify.call(_.m.JSON,{a:[3,!0,new Date(0)],c:function(){}})&&!0===He("true")&&3===He('[{"a":3}]')[0].a}catch(b){}Ee=Ge&&!He("[00]")&&!He('"\u0007"')&&!He('"\\0"')&&!He('"\\v"')}finally{Fe=a}}};_.kf=function(a){if(-1===Fe)return!1;jf();return(Ee?He:hf)(a)};
_.lf=function(a){if(-1!==Fe)return jf(),Ge?_.m.JSON.stringify.call(_.m.JSON,a):Qe(a)};mf=!Date.prototype.toISOString||"function"!==typeof Date.prototype.toISOString||"1970-01-01T00:00:00.000Z"!==(new Date(0)).toISOString();
nf=function(){var a=Date.prototype.getUTCFullYear.call(this);return[0>a?"-"+String(1E6-a).substr(1):9999>=a?String(1E4+a).substr(1):"+"+String(1E6+a).substr(1),"-",String(101+Date.prototype.getUTCMonth.call(this)).substr(1),"-",String(100+Date.prototype.getUTCDate.call(this)).substr(1),"T",String(100+Date.prototype.getUTCHours.call(this)).substr(1),":",String(100+Date.prototype.getUTCMinutes.call(this)).substr(1),":",String(100+Date.prototype.getUTCSeconds.call(this)).substr(1),".",String(1E3+Date.prototype.getUTCMilliseconds.call(this)).substr(1), "Z"].join("")};Date.prototype.toISOString=mf?nf:Date.prototype.toISOString;

var hl;hl=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?#]*)?\/u\/(\d)\//;
_.il=function(a){var b=_.I("googleapis.config/sessionIndex");"string"===typeof b&&254<b.length&&(b=null);null==b&&(b=window.__X_GOOG_AUTHUSER);"string"===typeof b&&254<b.length&&(b=null);if(null==b){var c=window.google;c&&(b=c.authuser)}"string"===typeof b&&254<b.length&&(b=null);null==b&&(a=a||window.location.href,b=_.ee(a,"authuser")||null,null==b&&(b=(b=a.match(hl))?b[1]:null));if(null==b)return null;b=String(b);254<b.length&&(b=null);return b};

var nl=function(){this.hj=-1};_.ol=function(){this.hj=64;this.Bc=[];this.Uw=[];this.iO=[];this.Iu=[];this.Iu[0]=128;for(var a=1;a<this.hj;++a)this.Iu[a]=0;this.Hv=this.Tm=0;this.reset()};_.z(_.ol,nl);_.ol.prototype.reset=function(){this.Bc[0]=1732584193;this.Bc[1]=4023233417;this.Bc[2]=2562383102;this.Bc[3]=271733878;this.Bc[4]=3285377520;this.Hv=this.Tm=0};
var pl=function(a,b,c){c||(c=0);var d=a.iO;if(_.v(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.Bc[0];c=a.Bc[1];var h=a.Bc[2],k=a.Bc[3],l=a.Bc[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=k^c&(h^k);var n=1518500249}else f=c^h^k,n=1859775393;else 60>e?(f=c&h|k&(c|h),n=2400959708):
(f=c^h^k,n=3395469782);f=(b<<5|b>>>27)+f+l+n+d[e]&4294967295;l=k;k=h;h=(c<<30|c>>>2)&4294967295;c=b;b=f}a.Bc[0]=a.Bc[0]+b&4294967295;a.Bc[1]=a.Bc[1]+c&4294967295;a.Bc[2]=a.Bc[2]+h&4294967295;a.Bc[3]=a.Bc[3]+k&4294967295;a.Bc[4]=a.Bc[4]+l&4294967295};
_.ol.prototype.update=function(a,b){if(null!=a){_.r(b)||(b=a.length);for(var c=b-this.hj,d=0,e=this.Uw,f=this.Tm;d<b;){if(0==f)for(;d<=c;)pl(this,a,d),d+=this.hj;if(_.v(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.hj){pl(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.hj){pl(this,e);f=0;break}}this.Tm=f;this.Hv+=b}};
_.ol.prototype.digest=function(){var a=[],b=8*this.Hv;56>this.Tm?this.update(this.Iu,56-this.Tm):this.update(this.Iu,this.hj-(this.Tm-56));for(var c=this.hj-1;56<=c;c--)this.Uw[c]=b&255,b/=256;pl(this,this.Uw);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.Bc[c]>>d&255,++b;return a};

_.ql=function(){this.mC=new _.ol};_.g=_.ql.prototype;_.g.reset=function(){this.mC.reset()};_.g.fL=function(a){this.mC.update(a)};_.g.oF=function(){return this.mC.digest()};_.g.KC=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.fL(b)};_.g.zg=function(){for(var a=this.oF(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

var Nm,Mm,Tm,Um,Om,Rm,Pm,Vm,Qm;_.Sm=function(){if(Mm){var a=new _.Xd.Uint32Array(1);Nm.getRandomValues(a);a=Number("0."+a[0])}else a=Om,a+=(0,window.parseInt)(Pm.substr(0,20),16),Pm=Qm(Pm),a/=Rm+Math.pow(16,20);return a};Nm=_.Xd.crypto;Mm=!1;Tm=0;Um=0;Om=1;Rm=0;Pm="";Vm=function(a){a=a||_.Xd.event;var b=a.screenX+a.clientX<<16;b+=a.screenY+a.clientY;b*=(new Date).getTime()%1E6;Om=Om*b%Rm;0<Tm&&++Um==Tm&&_.ie(_.Xd,"mousemove",Vm,"remove","de")};Qm=function(a){var b=new _.ql;b.KC(a);return b.zg()};
Mm=!!Nm&&"function"==typeof Nm.getRandomValues;Mm||(Rm=1E6*(window.screen.width*window.screen.width+window.screen.height),Pm=Qm(_.Yd.cookie+"|"+_.Yd.location+"|"+(new Date).getTime()+"|"+Math.random()),Tm=_.I("random/maxObserveMousemove")||0,0!=Tm&&_.me(_.Xd,"mousemove",Vm));

var Xm,an,bn,cn,dn,en,fn,gn,hn,jn,kn,ln,mn,qn,sn,tn,un,vn,wn,xn;_.Wm=function(a,b){b=b instanceof _.Zc?b:_.ed(b);a.href=_.$c(b)};_.Ym=function(a){return!!a&&"object"===typeof a&&_.$d.test(a.push)};_.Zm=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.$m=function(a,b){if(!a)throw Error(b||"");};an=/&/g;bn=/</g;cn=/>/g;dn=/"/g;en=/'/g;fn=function(a){return String(a).replace(an,"&amp;").replace(bn,"&lt;").replace(cn,"&gt;").replace(dn,"&quot;").replace(en,"&#39;")};gn=/[\ud800-\udbff][\udc00-\udfff]|[^!-~]/g;
hn=/%([a-f]|[0-9a-fA-F][a-f])/g;jn=/^(https?|ftp|file|chrome-extension):$/i;
kn=function(a){a=String(a);a=a.replace(gn,function(a){try{return(0,window.encodeURIComponent)(a)}catch(f){return(0,window.encodeURIComponent)(a.replace(/^[^%]+$/g,"\ufffd"))}}).replace(_.ge,function(a){return a.replace(/%/g,"%25")}).replace(hn,function(a){return a.toUpperCase()});a=a.match(_.fe)||[];var b=_.G(),c=function(a){return a.replace(/\\/g,"%5C").replace(/\^/g,"%5E").replace(/`/g,"%60").replace(/\{/g,"%7B").replace(/\|/g,"%7C").replace(/\}/g,"%7D")},d=!!(a[1]||"").match(jn);b.Eo=c((a[1]||
"")+(a[2]||"")+(a[3]||(a[2]&&d?"/":"")));d=function(a){return c(a.replace(/\?/g,"%3F").replace(/#/g,"%23"))};b.query=a[5]?[d(a[5])]:[];b.jh=a[7]?[d(a[7])]:[];return b};ln=function(a){return a.Eo+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.jh.length?"#"+a.jh.join("&"):"")};mn=function(a,b){var c=[];if(a)for(var d in a)if(_.be(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};
_.nn=function(a,b,c,d){a=kn(a);a.query.push.apply(a.query,mn(b,d));a.jh.push.apply(a.jh,mn(c,d));return ln(a)};
_.on=function(a,b){var c=kn(b);b=c.Eo;c.query.length&&(b+="?"+c.query.join(""));c.jh.length&&(b+="#"+c.jh.join(""));var d="";2E3<b.length&&(c=b,b=b.substr(0,2E3),b=b.replace(_.he,""),d=c.substr(b.length));var e=a.createElement("div");a=a.createElement("a");c=kn(b);b=c.Eo;c.query.length&&(b+="?"+c.query.join(""));c.jh.length&&(b+="#"+c.jh.join(""));a.href=b;e.appendChild(a);e.innerHTML=e.innerHTML;b=String(e.firstChild.href);e.parentNode&&e.parentNode.removeChild(e);c=kn(b+d);b=c.Eo;c.query.length&&
(b+="?"+c.query.join(""));c.jh.length&&(b+="#"+c.jh.join(""));return b};_.pn=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;qn=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.rn=function(a,b){var c=_.ae(_.ne,"watt",_.G());_.ae(c,a,b)};sn=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?#]*)?\/b\/(\d{10,21})\//;
tn=function(a){var b=_.I("googleapis.config/sessionDelegate");"string"===typeof b&&21<b.length&&(b=null);null==b&&(b=(a=(a||window.location.href).match(sn))?a[1]:null);if(null==b)return null;b=String(b);21<b.length&&(b=null);return b};un=function(){var a=_.ne.onl;if(!a){a=_.G();_.ne.onl=a;var b=_.G();a.e=function(a){var c=b[a];c&&(delete b[a],c())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a};vn=function(a,b){b=b.onload;return"function"===typeof b?(un().a(a,b),b):null}; wn=function(a){_.$m(/^\w+$/.test(a),"Unsupported id - "+a);un();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};xn=function(a){un().r(a)};
var zn,An,En;_.yn={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};zn={allowtransparency:!0,onload:!0};An=0;_.Bn=function(a,b){var c=0;do var d=b.id||["I",An++,"_",(new Date).getTime()].join("");while(a.getElementById(d)&&5>++c);_.$m(5>c,"Error creating iframe id");return d};_.Cn=function(a,b){return a?b+"/"+a:""};
_.Dn=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.ce(d.queryParams||{},e);_.ce(d.fragmentParams||{},f);var h=d.pfname;var k=_.G();_.I("iframes/dropLegacyIdParam")||(k.id=c);k._gfid=c;k.parent=a.location.protocol+"//"+a.location.host;c=_.ee(a.location.href,"parent");h=h||"";!h&&c&&(h=_.ee(a.location.href,"_gfid","")||_.ee(a.location.href,"id",""),h=_.Cn(h,_.ee(a.location.href,"pfname","")));h||(c=_.kf(_.ee(a.location.href,"jcp","")))&&"object"==
typeof c&&(h=_.Cn(c.id,c.pfname));k.pfname=h;d.connectWithJsonParam&&(h={},h.jcp=_.lf(k),k=h);h=_.ee(b,"rpctoken")||e.rpctoken||f.rpctoken;h||(h=d.rpctoken||String(Math.round(1E8*_.Sm())),k.rpctoken=h);d.rpctoken=h;_.ce(k,d.connectWithQueryParams?e:f);k=a.location.href;a=_.G();(h=_.ee(k,"_bsh",_.ne.bsh))&&(a._bsh=h);(k=_.ne.dpo?_.ne.h:_.ee(k,"jsh",_.ne.h))&&(a.jsh=k);d.hintInFragment?_.ce(a,f):_.ce(a,e);return _.nn(b,e,f,d.paramsSerializer)};
En=function(a){_.$m(!a||_.pn.test(a),"Illegal url for new iframe - "+a)};
_.Fn=function(a,b,c,d,e){En(c.src);var f,h=vn(d,c),k=h?wn(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+fn(String(c.frameborder))+'" scrolling="'+fn(String(c.scrolling))+'" '+k+' name="'+fn(String(c.name))+'"/>'))}catch(n){}finally{f||(f=a.createElement("iframe"),h&&(f.onload=function(){f.onload=null;h.call(this)},xn(d)))}f.setAttribute("ng-non-bindable","");for(var l in c)a=c[l],"style"===l&&"object"===typeof a?_.ce(a,f.style):zn[l]||f.setAttribute(l,String(a));(l=e&& e.beforeNode||null)||e&&e.dontclear||qn(b);b.insertBefore(f,l);f=l?l.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var Gn,Jn;Gn=/^:[\w]+$/;_.Hn=/:([a-zA-Z_]+):/g;_.In=function(){var a=_.il()||"0",b=tn();var c=_.il(void 0)||a;var d=tn(void 0),e="";c&&(e+="u/"+(0,window.encodeURIComponent)(String(c))+"/");d&&(e+="b/"+(0,window.encodeURIComponent)(String(d))+"/");c=e||null;(e=(d=!1===_.I("isLoggedIn"))?"_/im/":"")&&(c="");var f=_.I("iframes/:socialhost:"),h=_.I("iframes/:im_socialhost:");return Xm={socialhost:f,ctx_socialhost:d?h:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};
Jn=function(a,b){return _.In()[b]||""};_.Kn=function(a){return _.on(_.Yd,a.replace(_.Hn,Jn))};_.Ln=function(a){var b=a;Gn.test(a)&&(b=_.I("iframes/"+b.substring(1)+"/url"),_.$m(!!b,"Unknown iframe url config for - "+a));return _.Kn(b)};
_.Mn=function(a,b,c){var d=c||{};c=d.attributes||{};_.$m(!(d.allowPost||d.forcePost)||!c.onload,"onload is not supported by post iframe (allowPost or forcePost)");a=_.Ln(a);c=b.ownerDocument||_.Yd;var e=_.Bn(c,d);a=_.Dn(c,a,e,d);var f=_.G();_.ce(_.yn,f);_.ce(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;var h=d||{},k=!!h.allowPost;if(h.forcePost||k&&2E3<a.length){h=kn(a);f.src="";f["data-postorigin"]=a;a=_.Fn(c,b,f,e);if(-1!=window.navigator.userAgent.indexOf("WebKit")){var l=a.contentWindow.document;
l.open();f=l.createElement("div");k={};var n=e+"_inner";k.name=n;k.src="";k.style="display:none";_.Fn(c,f,k,n,d)}f=(d=h.query[0])?d.split("&"):[];d=[];for(k=0;k<f.length;k++)n=f[k].split("=",2),d.push([(0,window.decodeURIComponent)(n[0]),(0,window.decodeURIComponent)(n[1])]);h.query=[];f=ln(h);_.$m(_.pn.test(f),"Invalid URL: "+f);h=c.createElement("form");h.action=f;h.method="POST";h.target=e;h.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type="hidden",f.name=d[e][0],f.value= d[e][1],h.appendChild(f);b.appendChild(h);h.submit();h.parentNode.removeChild(h);l&&l.close();b=a}else b=_.Fn(c,b,f,e,d);return b};

_.w("gapi.iframes.create",_.Mn);
_.w("gadgets.json.stringify",_.lf);_.w("gadgets.json.parse",_.kf);
_.bk=window.gapi&&window.gapi.util||{};
_.dk=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a&&"chrome-search"!==a)throw Error("p");c="";var d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1);b=b.substring(0,d);if("http"=== a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c};

_.bk.Qa=function(a){return _.dk(a)};
_.Ae=window.console;_.Be=function(a){_.Ae&&_.Ae.log&&_.Ae.log(a)};_.Ce=function(){};
_.L=_.L||{};
_.L=_.L||{};
(function(){var a=null;_.L.qc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");e=window.decodeURIComponent?window.decodeURIComponent:window.unescape;f=0;for(var h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k);k=b[f].substring(k+1);k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(n){}}}c&&(a=d);return d}; _.L.qc()})();
_.w("gadgets.util.getUrlParameters",_.L.qc);
_.ee(_.Xd.location.href,"rpctoken")&&_.me(_.Yd,"unload",function(){});
var fm=function(){this.ur={lJ:Zl?"../"+Zl:null,DP:$l,CG:am,P7:bm,yG:cm,w8:dm};this.Ae=_.Xd;this.$I=this.zP;this.kQ=/MSIE\s*[0-8](\D|$)/.test(window.navigator.userAgent);if(this.ur.lJ){this.Ae=this.ur.CG(this.Ae,this.ur.lJ);var a=this.Ae.document,b=a.createElement("script");b.setAttribute("type","text/javascript");b.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(b);this.$I=this.Ae.doPostMsg}this.nC={};this.IC={};a=(0,_.B)(this.fz,
this);_.me(this.Ae,"message",a);_.ae(_.ne,"RPMQ",[]).push(a);this.Ae!=this.Ae.parent&&em(this,this.Ae.parent,"{h:'"+(0,window.escape)(this.Ae.name)+"'}","*")},gm=function(a){var b=null;0===a.indexOf("{h:'")&&a.indexOf("'}")===a.length-2&&(b=(0,window.unescape)(a.substring(4,a.length-2)));return b},hm=function(a){if(!/^\s*{/.test(a))return!1;a=_.kf(a);return null!==a&&"object"===typeof a&&!!a.g};
fm.prototype.fz=function(a){var b=String(a.data);(0,_.Ce)("gapi.rpc.receive("+bm+"): "+(!b||512>=b.length?b:b.substr(0,512)+"... ("+b.length+" bytes)"));var c=0!==b.indexOf("!_");c||(b=b.substring(2));var d=hm(b);if(!c&&!d){if(!d&&(c=gm(b))){if(this.nC[c])this.nC[c]();else this.IC[c]=1;return}var e=a.origin,f=this.ur.DP;this.kQ?_.Xd.setTimeout(function(){f(b,e)},0):f(b,e)}};fm.prototype.yc=function(a,b){".."===a||this.IC[a]?(b(),delete this.IC[a]):this.nC[a]=b};
var em=function(a,b,c,d){var e=hm(c)?"":"!_";(0,_.Ce)("gapi.rpc.send("+bm+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));a.$I(b,e+c,d)};fm.prototype.zP=function(a,b,c){a.postMessage(b,c)};fm.prototype.send=function(a,b,c){(a=this.ur.CG(this.Ae,a))&&!a.closed&&em(this,a,b,c)};
var im,jm,km,lm,mm,nm,om,pm,Zl,bm,qm,rm,sm,tm,am,cm,um,vm,Am,Bm,Dm,dm,Fm,Em,wm,xm,Gm,$l,Hm,Im;im=0;jm=[];km={};lm={};mm=_.L.qc;nm=mm();om=nm.rpctoken;pm=nm.parent||_.Yd.referrer;Zl=nm.rly;bm=Zl||(_.Xd!==_.Xd.top||_.Xd.opener)&&_.Xd.name||"..";qm=null;rm={};sm=function(){};tm={send:sm,yc:sm};
am=function(a,b){"/"==b.charAt(0)&&(b=b.substring(1),a=_.Xd.top);for(b=b.split("/");b.length;){var c=b.shift();"{"==c.charAt(0)&&"}"==c.charAt(c.length-1)&&(c=c.substring(1,c.length-1));if(".."===c)a=a==a.parent?a.opener:a.parent;else if(".."!==c&&a.frames[c]){if(a=a.frames[c],!("postMessage"in a))throw"Not a window";}else return null}return a};cm=function(a){return(a=km[a])&&a.Fv};
um=function(a){if(a.f in{})return!1;var b=a.t,c=km[a.r];a=a.origin;return c&&(c.Fv===b||!c.Fv&&!b)&&(a===c.origin||"*"===c.origin)};vm=function(a){var b=a.id.split("/"),c=b[b.length-1],d=a.origin;return function(a){var b=a.origin;return a.f==c&&(d==b||"*"==d)}};_.ym=function(a,b,c){a=wm(a);lm[a.name]={Dg:b,mq:a.mq,Yn:c||um};xm()};_.zm=function(a){delete lm[wm(a).name]};Am={};Bm=function(a,b){(a=Am["_"+a])&&a[1](this)&&a[0].call(this,b)};
Dm=function(a){var b=a.c;if(!b)return sm;var c=a.r,d=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,0);a.unshift(c,d+"__cb",null,b);_.Cm.apply(null,a)}};dm=function(a){qm=a};Fm=function(a){rm[a]||(rm[a]=_.Xd.setTimeout(function(){rm[a]=!1;Em(a)},0))};Em=function(a){var b=km[a];if(b&&b.ready){var c=b.cB;for(b.cB=[];c.length;)tm.send(a,_.lf(c.shift()),b.origin)}};wm=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),mq:!0}:{name:a,mq:!1}};
xm=function(){for(var a=_.I("rpc/residenceSec")||60,b=(new Date).getTime()/1E3,c=0,d;d=jm[c];++c){var e=d.Ll;if(!e||0<a&&b-d.timestamp>a)jm.splice(c,1),--c;else{var f=e.s,h=lm[f]||lm["*"];if(h)if(jm.splice(c,1),--c,e.origin=d.origin,d=Dm(e),e.callback=d,h.Yn(e)){if("__cb"!==f&&!!h.mq!=!!e.g)break;e=h.Dg.apply(e,e.a);void 0!==e&&d(e)}else(0,_.Ce)("gapi.rpc.rejected("+bm+"): "+f)}}};Gm=function(a,b,c){jm.push({Ll:a,origin:b,timestamp:(new Date).getTime()/1E3});c||xm()};
$l=function(a,b){a=_.kf(a);Gm(a,b,!1)};Hm=function(a){for(;a.length;)Gm(a.shift(),this.origin,!0);xm()};Im=function(a){var b=!1;a=a.split("|");var c=a[0];0<=c.indexOf("/")&&(b=!0);return{id:c,origin:a[1]||"*",Oz:b}};
_.Jm=function(a,b,c,d){var e=Im(a);d&&(_.Xd.frames[e.id]=_.Xd.frames[e.id]||d);a=e.id;if(!km.hasOwnProperty(a)){c=c||null;d=e.origin;if(".."===a)d=_.bk.Qa(pm),c=c||om;else if(!e.Oz){var f=_.Yd.getElementById(a);f&&(f=f.src,d=_.bk.Qa(f),c=c||mm(f).rpctoken)}"*"===e.origin&&d||(d=e.origin);km[a]={Fv:c,cB:[],origin:d,aX:b,fJ:function(){var b=a;km[b].ready=1;Em(b)}};tm.yc(a,km[a].fJ)}return km[a].fJ};
_.Cm=function(a,b,c,d){a=a||"..";_.Jm(a);a=a.split("|",1)[0];var e=b,f=[].slice.call(arguments,3),h=c,k=bm,l=om,n=km[a],p=k,q=Im(a);if(n&&".."!==a){if(q.Oz){if(!(l=km[a].aX)){l=qm?qm.substring(1).split("/"):[bm];p=l.length-1;for(var t=_.Xd.parent;t!==_.Xd.top;){var x=t.parent;if(!p--){for(var u=null,A=x.frames.length,E=0;E<A;++E)x.frames[E]==t&&(u=E);l.unshift("{"+u+"}")}t=x}l="/"+l.join("/")}p=l}else p=k="..";l=n.Fv}h&&q?(n=um,q.Oz&&(n=vm(q)),Am["_"+ ++im]=[h,n],h=im):h=null;f={s:e,f:k,r:p,t:l,c:h, a:f};e=wm(e);f.s=e.name;f.g=e.mq;km[a].cB.push(f);Fm(a)};if("function"===typeof _.Xd.postMessage||"object"===typeof _.Xd.postMessage)tm=new fm,_.ym("__cb",Bm,function(){return!0}),_.ym("_processBatch",Hm,function(){return!0}),_.Jm("..");

_.Vf=function(a,b){return _.v(b)?a.getElementById(b):b};_.Wf=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Xf=function(a,b){a:{for(var c=a.length,d=_.v(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:_.v(a)?a.charAt(b):a[b]};
_.Yf=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.Pd(a),a.appendChild(_.Ed(a).createTextNode(String(b)))};_.Zf=[];_.$f=[];_.ag=!1;_.bg=function(a){_.Zf[_.Zf.length]=a;if(_.ag)for(var b=0;b<_.$f.length;b++)a((0,_.B)(_.$f[b].wrap,_.$f[b]))};

_.Sg=function(a){return function(){return a}}(!0);
var Yg;_.Tg=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Tg);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.z(_.Tg,Error);_.Tg.prototype.name="CustomError";_.Ug=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;for(c in b)if(!(c in a))return!1;return!0};_.Vg=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.Wg=function(a,b){a.src=_.Vc(b)};_.Xg=function(a){return a};Yg=function(a,b){this.uP=a;this.PW=b;this.wu=0;this.Me=null}; Yg.prototype.get=function(){if(0<this.wu){this.wu--;var a=this.Me;this.Me=a.next;a.next=null}else a=this.uP();return a};Yg.prototype.put=function(a){this.PW(a);100>this.wu&&(this.wu++,a.next=this.Me,this.Me=a)};
var Zg,ah,bh,$g;Zg=function(a){_.m.setTimeout(function(){throw a;},0)};_.ch=function(a){a=$g(a);!_.Za(_.m.setImmediate)||_.m.Window&&_.m.Window.prototype&&!_.Vb("Edge")&&_.m.Window.prototype.setImmediate==_.m.setImmediate?(ah||(ah=bh()),ah(a)):_.m.setImmediate(a)};
bh=function(){var a=_.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.Vb("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=(0,_.B)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.cc()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.r(c.next)){c=c.next;var a=c.cb;c.cb=null;a()}};return function(a){d.next={cb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.m.setTimeout(a,0)}};$g=_.Xg;_.bg(function(a){$g=a});
var dh=function(){this.Sv=this.bo=null},fh=new Yg(function(){return new eh},function(a){a.reset()});dh.prototype.add=function(a,b){var c=fh.get();c.set(a,b);this.Sv?this.Sv.next=c:this.bo=c;this.Sv=c};dh.prototype.remove=function(){var a=null;this.bo&&(a=this.bo,this.bo=this.bo.next,this.bo||(this.Sv=null),a.next=null);return a};var eh=function(){this.next=this.scope=this.Dg=null};eh.prototype.set=function(a,b){this.Dg=a;this.scope=b;this.next=null}; eh.prototype.reset=function(){this.next=this.scope=this.Dg=null};
var gh,hh,ih,jh,lh;_.kh=function(a,b){gh||hh();ih||(gh(),ih=!0);jh.add(a,b)};hh=function(){if(-1!=String(_.m.Promise).indexOf("[native code]")){var a=_.m.Promise.resolve(void 0);gh=function(){a.then(lh)}}else gh=function(){_.ch(lh)}};ih=!1;jh=new dh;lh=function(){for(var a;a=jh.remove();){try{a.Dg.call(a.scope)}catch(b){Zg(b)}fh.put(a)}ih=!1};
_.mh=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};_.nh=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var qh,rh,Bh;_.ph=function(a,b){this.Ba=0;this.Ii=void 0;this.um=this.jj=this.Za=null;this.vt=this.dy=!1;if(a!=_.Va)try{var c=this;a.call(b,function(a){oh(c,2,a)},function(a){oh(c,3,a)})}catch(d){oh(this,3,d)}};qh=function(){this.next=this.context=this.mn=this.xq=this.wk=null;this.yo=!1};qh.prototype.reset=function(){this.context=this.mn=this.xq=this.wk=null;this.yo=!1};rh=new Yg(function(){return new qh},function(a){a.reset()});_.sh=function(a,b,c){var d=rh.get();d.xq=a;d.mn=b;d.context=c;return d};
_.th=function(a){if(a instanceof _.ph)return a;var b=new _.ph(_.Va);oh(b,2,a);return b};_.uh=function(a){return new _.ph(function(b,c){c(a)})};_.wh=function(a,b,c){vh(a,b,c,null)||_.kh(_.Wf(b,a))};_.yh=function(){var a,b,c=new _.ph(function(c,e){a=c;b=e});return new xh(c,a,b)};_.ph.prototype.then=function(a,b,c){return _.zh(this,_.Za(a)?a:null,_.Za(b)?b:null,c)};_.mh(_.ph);_.ph.prototype.RK=_.ca(6);_.ph.prototype.cancel=function(a){0==this.Ba&&_.kh(function(){var b=new Ah(a);Bh(this,b)},this)};
Bh=function(a,b){if(0==a.Ba)if(a.Za){var c=a.Za;if(c.jj){for(var d=0,e=null,f=null,h=c.jj;h&&(h.yo||(d++,h.wk==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.Ba&&1==d?Bh(c,b):(f?(d=f,d.next==c.um&&(c.um=d),d.next=d.next.next):Ch(c),Dh(c,e,3,b)))}a.Za=null}else oh(a,3,b)};_.Fh=function(a,b){a.jj||2!=a.Ba&&3!=a.Ba||Eh(a);a.um?a.um.next=b:a.jj=b;a.um=b};
_.zh=function(a,b,c,d){var e=_.sh(null,null,null);e.wk=new _.ph(function(a,h){e.xq=b?function(c){try{var e=b.call(d,c);a(e)}catch(n){h(n)}}:a;e.mn=c?function(b){try{var e=c.call(d,b);!_.r(e)&&b instanceof Ah?h(b):a(e)}catch(n){h(n)}}:h});e.wk.Za=a;_.Fh(a,e);return e.wk};_.ph.prototype.ZY=function(a){this.Ba=0;oh(this,2,a)};_.ph.prototype.$Y=function(a){this.Ba=0;oh(this,3,a)};
var oh=function(a,b,c){0==a.Ba&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.Ba=1,vh(c,a.ZY,a.$Y,a)||(a.Ii=c,a.Ba=b,a.Za=null,Eh(a),3!=b||c instanceof Ah||Gh(a,c)))},vh=function(a,b,c,d){if(a instanceof _.ph)return _.Fh(a,_.sh(b||_.Va,c||null,d)),!0;if(_.nh(a))return a.then(b,c,d),!0;if(_.$a(a))try{var e=a.then;if(_.Za(e))return Hh(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1},Hh=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=
!0,d.call(e,a))};try{b.call(a,h,k)}catch(l){k(l)}},Eh=function(a){a.dy||(a.dy=!0,_.kh(a.WP,a))},Ch=function(a){var b=null;a.jj&&(b=a.jj,a.jj=b.next,b.next=null);a.jj||(a.um=null);return b};_.ph.prototype.WP=function(){for(var a;a=Ch(this);)Dh(this,a,this.Ba,this.Ii);this.dy=!1};
var Dh=function(a,b,c,d){if(3==c&&b.mn&&!b.yo)for(;a&&a.vt;a=a.Za)a.vt=!1;if(b.wk)b.wk.Za=null,Ih(b,c,d);else try{b.yo?b.xq.call(b.context):Ih(b,c,d)}catch(e){Jh.call(null,e)}rh.put(b)},Ih=function(a,b,c){2==b?a.xq.call(a.context,c):a.mn&&a.mn.call(a.context,c)},Gh=function(a,b){a.vt=!0;_.kh(function(){a.vt&&Jh.call(null,b)})},Jh=Zg,Ah=function(a){_.Tg.call(this,a)};_.z(Ah,_.Tg);Ah.prototype.name="cancel";var xh=function(a,b,c){this.promise=a;this.resolve=b;this.reject=c};

_.Km=function(a){return new _.ph(a)};
_.Lm=_.Lm||{};_.Lm.cS=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

_.Lm=_.Lm||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Lm.Uc=function(){var b=_.Lm.cS().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift();d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight){var h=f.offsetTop+f.offsetHeight+a(f,"margin-bottom");b=Math.max(b,h)}c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

_.Nn=function(a){this.R=a};_.g=_.Nn.prototype;_.g.value=function(){return this.R};_.g.$j=function(a){this.R.width=a;return this};_.g.Ad=function(){return this.R.width};_.g.Xj=function(a){this.R.height=a;return this};_.g.Uc=function(){return this.R.height};_.g.Fd=function(a){this.R.style=a;return this};_.g.Yk=_.ca(11);
var On=function(a){this.R=a};_.g=On.prototype;_.g.Ln=function(a){this.R.anchor=a;return this};_.g.nf=function(){return this.R.anchor};_.g.LB=function(a){this.R.anchorPosition=a;return this};_.g.Xj=function(a){this.R.height=a;return this};_.g.Uc=function(){return this.R.height};_.g.$j=function(a){this.R.width=a;return this};_.g.Ad=function(){return this.R.width};
_.Pn=function(a){this.R=a||{}};_.g=_.Pn.prototype;_.g.value=function(){return this.R};_.g.setUrl=function(a){this.R.url=a;return this};_.g.getUrl=function(){return this.R.url};_.g.Fd=function(a){this.R.style=a;return this};_.g.Yk=_.ca(10);_.g.Oi=function(a){this.R.id=a};_.g.ka=function(){return this.R.id};_.g.Zj=_.ca(12);_.Qn=function(a,b){a.R.queryParams=b;return a};_.Rn=function(a,b){a.R.relayOpen=b;return a};_.Pn.prototype.Mn=_.ca(13);_.Pn.prototype.getContext=function(){return this.R.context};
_.Pn.prototype.Nc=function(){return this.R.openerIframe};_.Sn=function(a){return new On(a.R)};_.Pn.prototype.Em=function(){this.R.attributes=this.R.attributes||{};return new _.Nn(this.R.attributes)};_.Tn=function(a){a.R.connectWithQueryParams=!0;return a};

var Un,$n,ao,bo,io,ho;_.Nn.prototype.Yk=_.Sa(11,function(){return this.R.style});_.Pn.prototype.Yk=_.Sa(10,function(){return this.R.style});Un=function(a,b){a.R.onload=b};_.Vn=function(a){a.R.closeClickDetection=!0};_.Wn=function(a){return a.R.rpctoken};_.Xn=function(a,b){a.R.messageHandlers=b;return a};_.Yn=function(a,b){a.R.messageHandlersFilter=b;return a};_.Zn=function(a){a.R.waitForOnload=!0;return a};$n=function(a){return(a=a.R.timeout)?a:null};
_.eo=function(a,b,c){if(a){_.$m(_.Ym(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};_.fo=function(a,b,c){if(a)if(_.Ym(a))_.eo(a,b,c);else{_.$m("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.be(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};
_.go=function(a){return new _.ph(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},k=0,l;k<a.length;k++)l=a[k],_.wh(l,_.Wf(f,k),h);else b(e)})};io=function(a){this.resolve=this.reject=null;this.promise=_.Km((0,_.B)(function(a,c){this.resolve=a;this.reject=c},this));a&&(this.promise=ho(this.promise,a))};ho=function(a,b){return a.then(function(a){try{b(a)}catch(d){}return a})};
_.jo=function(a){this.R=a||{}};_.z(_.jo,_.Pn);_.ko=function(a,b){a.R.frameName=b;return a};_.jo.prototype.zd=function(){return this.R.frameName};_.lo=function(a,b){a.R.rpcAddr=b;return a};_.jo.prototype.Wk=function(){return this.R.rpcAddr};_.mo=function(a,b){a.R.retAddr=b;return a};_.no=function(a){return a.R.retAddr};_.jo.prototype.Jh=function(a){this.R.origin=a;return this};_.jo.prototype.Qa=function(){return this.R.origin};_.jo.prototype.Pi=function(a){this.R.setRpcReady=a;return this};_.oo=function(a){return a.R.setRpcReady}; _.jo.prototype.On=function(a){this.R.context=a};var po=function(a,b){a.R._rpcReadyFn=b};_.jo.prototype.Ga=function(){return this.R.iframeEl};
var qo,uo,to;qo=/^[\w\.\-]*$/;_.ro=function(a){return a.sd===a.getContext().sd};_.Q=function(){return!0};_.so=function(a){for(var b=_.G(),c=0;c<a.length;c++)b[a[c]]=!0;return function(a){return!!b[a.sd]}};uo=function(a,b,c){return function(d){if(!b.Db){_.$m(this.origin===b.sd,"Wrong origin "+this.origin+" != "+b.sd);var e=this.callback;d=to(a,d,b);!c&&0<d.length&&_.go(d).then(e)}}};to=function(a,b,c){a=ao[a];if(!a)return[];for(var d=[],e=0;e<a.length;e++)d.push(_.th(a[e].call(c,b,c)));return d};
_.vo=function(a,b,c){_.$m("_default"!=a,"Cannot update default api");bo[a]={map:b,filter:c}};_.wo=function(a,b,c){_.$m("_default"!=a,"Cannot update default api");_.ae(bo,a,{map:{},filter:_.ro}).map[b]=c};_.xo=function(a,b){_.ae(bo,"_default",{map:{},filter:_.Q}).map[a]=b;_.fo(_.co.Ce,function(c){c.register(a,b,_.Q)})};_.yo=function(){return _.co};
_.Ao=function(a){a=a||{};this.Db=!1;this.WI=_.G();this.Ce=_.G();this.Ae=a._window||_.Xd;this.ud=this.Ae.location.href;this.XI=(this.OA=zo(this.ud,"parent"))?zo(this.ud,"pfname"):"";this.ya=this.OA?zo(this.ud,"_gfid")||zo(this.ud,"id"):"";this.mf=_.Cn(this.ya,this.XI);this.sd=_.bk.Qa(this.ud);if(this.ya){var b=new _.jo;_.lo(b,a._parentRpcAddr||"..");_.mo(b,a._parentRetAddr||this.ya);b.Jh(_.bk.Qa(this.OA||this.ud));_.ko(b,this.XI);this.Za=this.ej(b.value())}else this.Za=null};_.g=_.Ao.prototype;
_.g.Wm=_.ca(4);_.g.ua=function(){if(!this.Db){for(var a=0;a<this.Ce.length;a++)this.Ce[a].ua();this.Db=!0}};_.g.zd=function(){return this.mf};_.g.tb=function(){return this.Ae};_.g.mb=function(){return this.Ae.document};_.g.pv=_.ca(14);_.g.Cy=function(a){return this.WI[a]};
_.g.ej=function(a){_.$m(!this.Db,"Cannot attach iframe in disposed context");a=new _.jo(a);a.Wk()||_.lo(a,a.ka());_.no(a)||_.mo(a,"..");a.Qa()||a.Jh(_.bk.Qa(a.getUrl()));a.zd()||_.ko(a,_.Cn(a.ka(),this.mf));var b=a.zd();if(this.Ce[b])return this.Ce[b];var c=a.Wk(),d=c;a.Qa()&&(d=c+"|"+a.Qa());var e=_.no(a),f=_.Wn(a);f||(f=(f=a.Ga())&&(f.getAttribute("data-postorigin")||f.src)||a.getUrl(),f=_.ee(f,"rpctoken"));po(a,_.Jm(d,e,f,a.R._popupWindow));d=((window.gadgets||{}).rpc||{}).setAuthToken;f&&d&&d(c,
f);var h=new _.Bo(this,c,b,a),k=a.R.messageHandlersFilter;_.fo(a.R.messageHandlers,function(a,b){h.register(b,a,k)});_.oo(a)&&h.Pi();_.Co(h,"_g_rpcReady");return h};_.g.uB=function(a){_.ko(a,null);var b=a.ka();!b||qo.test(b)&&!this.tb().document.getElementById(b)||(_.Be("Ignoring requested iframe ID - "+b),a.Oi(null))};var zo=function(a,b){var c=_.ee(a,b);c||(c=_.kf(_.ee(a,"jcp",""))[b]);return c||""};
_.Ao.prototype.Ng=function(a){_.$m(!this.Db,"Cannot open iframe in disposed context");var b=new _.jo(a);Do(this,b);var c=b.zd();if(c&&this.Ce[c])return this.Ce[c];this.uB(b);c=b.getUrl();_.$m(c,"No url for new iframe");var d=b.R.queryParams||{};d.usegapi="1";_.Qn(b,d);d=this.VG&&this.VG(c,b);d||(d=b.R.where,_.$m(!!d,"No location for new iframe"),c=_.Mn(c,d,a),b.R.iframeEl=c,d=c.getAttribute("id"));_.lo(b,d).Oi(d);b.Jh(_.bk.Qa(b.R.eurl||""));this.cI&&this.cI(b,b.Ga());c=this.ej(a);c.dC&&c.dC(c,a);
(a=b.R.onCreate)&&a(c);b.R.disableRelayOpen||c.Ao("_open");return c};
var Eo=function(a,b,c){var d=b.R.canvasUrl;if(!d)return c;_.$m(!b.R.allowPost&&!b.R.forcePost,"Post is not supported when using canvas url");var e=b.getUrl();_.$m(e&&_.bk.Qa(e)===a.sd&&_.bk.Qa(d)===a.sd,"Wrong origin for canvas or hidden url "+d);b.setUrl(d);_.Zn(b);b.R.canvasUrl=null;return function(a){var b=a.tb(),d=b.location.hash;d=_.Ln(e)+(/#/.test(e)?d.replace(/^#/,"&"):d);b.location.replace(d);c&&c(a)}},Go=function(a,b,c){var d=b.R.relayOpen;if(d){var e=a.Za;d instanceof _.Bo?(e=d,_.Rn(b,0)):
0<Number(d)&&_.Rn(b,Number(d)-1);if(e){_.$m(!!e.NI,"Relaying iframe open is disabled");if(d=b.Yk())if(d=_.Fo[d])b.On(a),d(b.value()),b.On(null);b.R.openerIframe=null;c.resolve(e.NI(b));return!0}}return!1},Ko=function(a,b,c){var d=b.Yk();if(d)if(_.$m(!!_.Ho,"Defer style is disabled, when requesting style "+d),_.Io[d])Do(a,b);else return Jo(d,function(){_.$m(!!_.Io[d],"Fail to load style - "+d);c.resolve(a.open(b.value()))}),!0;return!1};
_.Ao.prototype.open=function(a,b){_.$m(!this.Db,"Cannot open iframe in disposed context");var c=new _.jo(a);b=Eo(this,c,b);var d=new io(b);(b=c.getUrl())&&c.setUrl(_.Ln(b));if(Go(this,c,d)||Ko(this,c,d)||Go(this,c,d))return d.promise;if(null!=$n(c)){var e=(0,window.setTimeout)(function(){h.Ga().src="about:blank";d.reject({timeout:"Exceeded time limit of :"+$n(c)+"milliseconds"})},$n(c)),f=d.resolve;d.resolve=function(a){(0,window.clearTimeout)(e);f(a)}}c.R.waitForOnload&&Un(c.Em(),function(){d.resolve(h)});
var h=this.Ng(a);c.R.waitForOnload||d.resolve(h);return d.promise};_.Ao.prototype.kG=_.ca(15);_.Bo=function(a,b,c,d){this.Db=!1;this.Ld=a;this.Ji=b;this.mf=c;this.Ha=d;this.En=_.no(this.Ha);this.sd=this.Ha.Qa();this.RT=this.Ha.Ga();this.FK=this.Ha.R.where;this.wn=[];this.Ao("_default");a=this.Ha.R.apis||[];for(b=0;b<a.length;b++)this.Ao(a[b]);this.Ld.Ce[c]=this};_.g=_.Bo.prototype;_.g.Wm=_.ca(3);
_.g.ua=function(){if(!this.Db){for(var a=0;a<this.wn.length;a++)this.unregister(this.wn[a]);delete _.co.Ce[this.zd()];this.Db=!0}};_.g.getContext=function(){return this.Ld};_.g.Wk=function(){return this.Ji};_.g.zd=function(){return this.mf};_.g.Ga=function(){return this.RT};_.g.Ya=function(){return this.FK};_.g.Ue=function(a){this.FK=a};_.g.Pi=function(){(0,this.Ha.R._rpcReadyFn)()};_.g.gK=function(a,b){this.Ha.value()[a]=b};_.g.Ky=function(a){return this.Ha.value()[a]};_.g.Mb=function(){return this.Ha.value()};
_.g.ka=function(){return this.Ha.ka()};_.g.Qa=function(){return this.sd};_.g.register=function(a,b,c){_.$m(!this.Db,"Cannot register handler on disposed iframe "+a);_.$m((c||_.ro)(this),"Rejecting untrusted message "+a);c=this.mf+":"+this.Ld.mf+":"+a;1==_.ae(ao,c,[]).push(b)&&(this.wn.push(a),_.ym(c,uo(c,this,"_g_wasClosed"===a)))};
_.g.unregister=function(a,b){var c=this.mf+":"+this.Ld.mf+":"+a,d=ao[c];d&&(b?(b=_.Zm.call(d,b),0<=b&&d.splice(b,1)):d.splice(0,d.length),0==d.length&&(b=_.Zm.call(this.wn,a),0<=b&&this.wn.splice(b,1),_.zm(c)))};_.g.MR=function(){return this.wn};_.g.Ao=function(a){this.Iw=this.Iw||[];if(!(0<=_.Zm.call(this.Iw,a))){this.Iw.push(a);a=bo[a]||{map:{}};for(var b in a.map)_.be(a.map,b)&&this.register(b,a.map[b],a.filter)}};
_.g.send=function(a,b,c,d){_.$m(!this.Db,"Cannot send message to disposed iframe - "+a);_.$m((d||_.ro)(this),"Wrong target for message "+a);c=new io(c);_.Cm(this.Ji,this.Ld.mf+":"+this.mf+":"+a,c.resolve,b);return c.promise};_.Co=function(a,b,c,d){return a.send(b,c,d,_.Q)};_.Bo.prototype.XV=function(a){return a};_.Bo.prototype.ping=function(a,b){return _.Co(this,"_g_ping",b,a)};ao=_.G();bo=_.G();_.co=new _.Ao;_.xo("_g_rpcReady",_.Bo.prototype.Pi);_.xo("_g_discover",_.Bo.prototype.MR); _.xo("_g_ping",_.Bo.prototype.XV);
var Jo,Do;_.Io=_.G();_.Fo=_.G();_.Ho=function(a){return _.Io[a]};Jo=function(a,b){_.de.load("gapi.iframes.style."+a,b)};Do=function(a,b){var c=b.Yk();if(c){b.Fd(null);var d=_.Io[c];_.$m(d,"No such style: "+c);b.On(a);d(b.value());b.On(null)}};var Lo,Mo;Lo={height:!0,width:!0};Mo=/^(?!-*(?:expression|(?:moz-)?binding))(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,2}|%)?|!important|)$/i;_.No=function(a){"number"===typeof a&&(a=String(a)+"px");return a};_.Bo.prototype.tb=function(){if(!_.ro(this))return null;var a=this.Ha.R._popupWindow;if(a)return a;var b=this.Ji.split("/");a=this.getContext().tb();for(var c=0;c<b.length&&a;c++){var d=b[c];a=".."===d?a==a.parent?a.opener:a.parent:a.frames[d]}return a};
var Oo=function(a,b){var c=a.Za,d=!0;b.filter&&(d=b.filter.call(b.sf,b.params));return _.th(d).then(function(d){return d&&c?(b.VI&&b.VI.call(a,b.params),d=b.sender?b.sender(b.params):_.Co(c,b.message,b.params),b.oZ?d.then(function(){return!0}):!0):!1})};
_.Ao.prototype.fx=function(a,b,c){a=Oo(this,{sender:function(a){var b=_.co.Za;_.fo(_.co.Ce,function(c){c!==b&&_.Co(c,"_g_wasClosed",a)});return _.Co(b,"_g_closeMe",a)},message:"_g_closeMe",params:a,sf:c,filter:this.Cy("onCloseSelfFilter")});b=new io(b);b.resolve(a);return b.promise};_.Ao.prototype.rB=function(a,b,c){a=a||{};b=new io(b);b.resolve(Oo(this,{message:"_g_restyleMe",params:a,sf:c,filter:this.Cy("onRestyleSelfFilter"),oZ:!0,VI:this.eL}));return b.promise};
_.Ao.prototype.eL=function(a){"auto"===a.height&&(a.height=_.Lm.Uc())};_.Po=function(a){var b={};if(a)for(var c in a)_.be(a,c)&&_.be(Lo,c)&&Mo.test(a[c])&&(b[c]=a[c]);return b};_.g=_.Bo.prototype;_.g.close=function(a,b){return _.Co(this,"_g_close",a,b)};_.g.Jq=function(a,b){return _.Co(this,"_g_restyle",a,b)};_.g.Cn=function(a,b){return _.Co(this,"_g_restyleDone",a,b)};_.g.hP=function(a){return this.getContext().fx(a,void 0,this)};
_.g.XW=function(a){if(a&&"object"===typeof a)return this.getContext().rB(a,void 0,this)};_.g.YW=function(a){var b=this.Ha.R.onRestyle;b&&b.call(this,a,this);a=a&&"object"===typeof a?_.Po(a):{};(b=this.Ga())&&a&&"object"===typeof a&&(_.be(a,"height")&&(a.height=_.No(a.height)),_.be(a,"width")&&(a.width=_.No(a.width)),_.ce(a,b.style))};
_.g.iP=function(a){var b=this.Ha.R.onClose;b&&b.call(this,a,this);this.VE&&this.VE()||(b=this.Ga())&&b.parentNode&&b.parentNode.removeChild(b);if(b=this.Ha.R.controller){var c={};c.frameName=this.zd();_.Co(b,"_g_disposeControl",c)}to(this.mf+":"+this.Ld.mf+":_g_wasClosed",a,this)};_.Ao.prototype.TJ=_.ca(16);_.Ao.prototype.iK=_.ca(17);_.Bo.prototype.kJ=_.ca(18);_.Bo.prototype.Rj=function(a,b){this.register("_g_wasClosed",a,b)};
_.Bo.prototype.rZ=function(){delete this.getContext().Ce[this.zd()];this.getContext().tb().setTimeout((0,_.B)(function(){this.ua()},this),0)};_.xo("_g_close",_.Bo.prototype.hP);_.xo("_g_closeMe",_.Bo.prototype.iP);_.xo("_g_restyle",_.Bo.prototype.XW);_.xo("_g_restyleMe",_.Bo.prototype.YW);_.xo("_g_wasClosed",_.Bo.prototype.rZ);

_.Bo.prototype.kJ=_.Sa(18,function(a,b){this.register("_g_wasRestyled",a,b)});_.g=_.Ao.prototype;_.g.iK=_.Sa(17,function(a){this.pv("onRestyleSelfFilter",a)});_.g.TJ=_.Sa(16,function(a){this.pv("onCloseSelfFilter",a)});_.g.kG=_.Sa(15,function(){return this.Za});_.g.pv=_.Sa(14,function(a,b){this.WI[a]=b});_.g.Wm=_.Sa(4,function(){return this.Db});_.Bo.prototype.Wm=_.Sa(3,function(){return this.Db});_.w("gapi.iframes.registerStyle",function(a,b){_.Io[a]=b});
_.w("gapi.iframes.registerBeforeOpenStyle",function(a,b){_.Fo[a]=b});_.w("gapi.iframes.getStyle",_.Ho);_.w("gapi.iframes.getBeforeOpenStyle",function(a){return _.Fo[a]});_.w("gapi.iframes.registerIframesApi",_.vo);_.w("gapi.iframes.registerIframesApiHandler",_.wo);_.w("gapi.iframes.getContext",_.yo);_.w("gapi.iframes.SAME_ORIGIN_IFRAMES_FILTER",_.ro);_.w("gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.Q);_.w("gapi.iframes.makeWhiteListIframesFilter",_.so);_.w("gapi.iframes.Context",_.Ao);
_.w("gapi.iframes.Context.prototype.isDisposed",_.Ao.prototype.Wm);_.w("gapi.iframes.Context.prototype.getWindow",_.Ao.prototype.tb);_.w("gapi.iframes.Context.prototype.getFrameName",_.Ao.prototype.zd);_.w("gapi.iframes.Context.prototype.getGlobalParam",_.Ao.prototype.Cy);_.w("gapi.iframes.Context.prototype.setGlobalParam",_.Ao.prototype.pv);_.w("gapi.iframes.Context.prototype.open",_.Ao.prototype.open);_.w("gapi.iframes.Context.prototype.openChild",_.Ao.prototype.Ng);
_.w("gapi.iframes.Context.prototype.getParentIframe",_.Ao.prototype.kG);_.w("gapi.iframes.Context.prototype.closeSelf",_.Ao.prototype.fx);_.w("gapi.iframes.Context.prototype.restyleSelf",_.Ao.prototype.rB);_.w("gapi.iframes.Context.prototype.setCloseSelfFilter",_.Ao.prototype.TJ);_.w("gapi.iframes.Context.prototype.setRestyleSelfFilter",_.Ao.prototype.iK);_.w("gapi.iframes.Iframe",_.Bo);_.w("gapi.iframes.Iframe.prototype.isDisposed",_.Bo.prototype.Wm);
_.w("gapi.iframes.Iframe.prototype.getContext",_.Bo.prototype.getContext);_.w("gapi.iframes.Iframe.prototype.getFrameName",_.Bo.prototype.zd);_.w("gapi.iframes.Iframe.prototype.getId",_.Bo.prototype.ka);_.w("gapi.iframes.Iframe.prototype.register",_.Bo.prototype.register);_.w("gapi.iframes.Iframe.prototype.unregister",_.Bo.prototype.unregister);_.w("gapi.iframes.Iframe.prototype.send",_.Bo.prototype.send);_.w("gapi.iframes.Iframe.prototype.applyIframesApi",_.Bo.prototype.Ao);
_.w("gapi.iframes.Iframe.prototype.getIframeEl",_.Bo.prototype.Ga);_.w("gapi.iframes.Iframe.prototype.getSiteEl",_.Bo.prototype.Ya);_.w("gapi.iframes.Iframe.prototype.setSiteEl",_.Bo.prototype.Ue);_.w("gapi.iframes.Iframe.prototype.getWindow",_.Bo.prototype.tb);_.w("gapi.iframes.Iframe.prototype.getOrigin",_.Bo.prototype.Qa);_.w("gapi.iframes.Iframe.prototype.close",_.Bo.prototype.close);_.w("gapi.iframes.Iframe.prototype.restyle",_.Bo.prototype.Jq);
_.w("gapi.iframes.Iframe.prototype.restyleDone",_.Bo.prototype.Cn);_.w("gapi.iframes.Iframe.prototype.registerWasRestyled",_.Bo.prototype.kJ);_.w("gapi.iframes.Iframe.prototype.registerWasClosed",_.Bo.prototype.Rj);_.w("gapi.iframes.Iframe.prototype.getParam",_.Bo.prototype.Ky);_.w("gapi.iframes.Iframe.prototype.setParam",_.Bo.prototype.gK);_.w("gapi.iframes.Iframe.prototype.ping",_.Bo.prototype.ping);

});
// Google Inc.
