version: "3"
services:
  test-opa:
    image: openpolicyagent/opa:1.3.0-static
    ports:
      - 8181:8181
    volumes:
      - ./policies:/policies
    command: ["run", "--server", "/policies"]
    expose:
      - 8181
