apiVersion: v1
kind: ConfigMap
metadata:
  name: "search-api-app-conf"
data:
  deploy-application.conf: {{ (mustRegexReplaceAllLiteral "^\\s*{" ((include "magda.search-api.appConfig" .) | fromJson | mustToPrettyJson) "{\n  include \"application\"") | quote }}