export {
    PREFIX,
    CommonPropsType,
    ExternalCompontType,
    HeaderNavItem,
    HeaderComponentProps,
    HeaderCompontType,
    ExternalHeaderCompontType,
    CopyRightItem,
    FooterNavLink,
    FooterNavLinkGroup,
    FooterComponentPropsType,
    FooterComponentType,
    ExternalFooterCompontType,
    DatasetEditButtonComponentPropsType,
    DatasetEditButtonComponentType,
    ExternalDatasetEditButtonCompontType,
    DatasetLikeButtonComponentPropsType,
    DatasetLikeButtonComponentType,
    ExternalDatasetLikeButtonCompontType,
    ExtraVisualisationSectionComponentPropsType,
    ExtraVisualisationSectionComponentType,
    ExternalExtraVisualisationSectionCompontType
} from "@magda/web-client/src/externalPluginComponents";
