{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1") .Values.global.enablePriorityClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: magda-8
value: 80000000
globalDefault: false
description: "Ordered importance class 1-10"
{{- end }}
