{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.controlPlaneSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controlPlaneSecret.name }}
type: Opaque
stringData:
  {{ .Values.controlPlaneSecret.key }}: {{ if $existing }}{{ index $existing.data .Values.controlPlaneSecret.key | b64dec | quote }}{{ else }}{{ randAlphaNum 48 | quote }}{{ end }}
