{{- if .Values.sandboxNamespaceResource.create }}
{{- $namespace := dig "agentWorkspace" "sandboxNamespace" .Values.sandboxNamespace .Values.global }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  {{- with .Values.sandboxNamespaceResource.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.sandboxNamespaceResource.labels }}
  labels:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
