apiVersion: v1
kind: ConfigMap
metadata:
  name: "registry-api-app-conf"
data:
  deploy-application.conf: {{ (mustRegexReplaceAllLiteral "^\\s*{" ((include "magda.registry-api.appConfig" .) | fromJson | mustToPrettyJson) "{\n  include \"application\"") | quote }}