{{- if .Values.autoCreateSecrets }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "storage-secrets") | default dict }}
{{- /* only attempt to create secret when secret not exists or the existing secret is part of current helm release */}}
{{- if or (empty $secret) (include "magda.isPartOfRelease" (dict "objectData" $secret "root" .) | empty | not) }}
{{- $secretData := (get $secret "data") | default dict }}
{{- $accesskey := (get $secretData "accesskey") | default (randAlphaNum 20 | b64enc) }}
{{- $secretkey := (get $secretData "secretkey") | default (randAlphaNum 40 | b64enc) }}
apiVersion: v1
kind: Secret
metadata:
  name: "storage-secrets"
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  accesskey: {{ $accesskey | quote }}
  secretkey: {{ $secretkey | quote }}
{{- end }}
{{- end }}