# -- migrator docker image settings
image: 
  name: "magda-migrator-registry-db"
  # repository: 
  # tag: 
  # pullPolicy: 
  # pullSecrets: 

vacuumJobImage: 
  name: "magda-postgres"
  # repository: 
  # tag: 
  # pullPolicy: 
  # pullSecrets: 

defaultImage:
  repository: "ghcr.io/magda-io"
  pullPolicy: IfNotPresent
  pullSecrets: false

# -- whether auto-create secret for client account password.
# After the migrator runs properly, a non-superuser DB account (named `client`) will be created.
# Its password will loaded from secret `{{ .Chart.Name }}-password` (e.g. `authorization-db-passwor`) & key: `password`.
# Set this option to `true` will make helm auto-create the secret with random password, ONLY when the secret not exists.
autoCreateSecret: true

# -- No. of retries before the migrator job is considered as failed.
# Failed Pods associated with the Job are recreated by the Job controller with an exponential back-off delay (10s, 20s, 40s ...) capped at six minutes.
migratorBackoffLimit: 6

magda-postgres:
  postgresql: 
    fullnameOverride: "registry-db-postgresql"
    nameOverride: "registry-db-postgresql"
    persistence:
      size: "100Gi"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
autoVacuum:
  enable: true
  # -- auto vacuum cronjob schedule string. specified using unix-cron format (in UTC timezone by default).
  # @default -- "0 19 * * *": 7:00PM UTC timezone (5:00AM in AEST Sydney timezone) daily
  schedule: "0 19 * * *" 